# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setup_main.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SetupMainWindow(object):
    def setupUi(self, SetupMainWindow):
        SetupMainWindow.setObjectName("SetupMainWindow")
        SetupMainWindow.resize(1768, 1006)
        self.centralwidget = QtWidgets.QWidget(SetupMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.scrollArea.setWidgetResizable(False)
        self.scrollArea.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 253, 985))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollAreaWidgetContents.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setContentsMargins(6, 0, 6, 0)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_SR830 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_SR830.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_SR830.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_SR830.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox_SR830.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_SR830.setObjectName("groupBox_SR830")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_SR830)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_SR830_Conn_Status = QtWidgets.QLabel(self.groupBox_SR830)
        self.label_SR830_Conn_Status.setStyleSheet("background: red\n"
"")
        self.label_SR830_Conn_Status.setText("")
        self.label_SR830_Conn_Status.setObjectName("label_SR830_Conn_Status")
        self.horizontalLayout_5.addWidget(self.label_SR830_Conn_Status)
        self.pushButton_SR830_Config = QtWidgets.QPushButton(self.groupBox_SR830)
        self.pushButton_SR830_Config.setObjectName("pushButton_SR830_Config")
        self.horizontalLayout_5.addWidget(self.pushButton_SR830_Config)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_SR830_Theta = QtWidgets.QLabel(self.groupBox_SR830)
        self.label_SR830_Theta.setText("")
        self.label_SR830_Theta.setObjectName("label_SR830_Theta")
        self.gridLayout.addWidget(self.label_SR830_Theta, 3, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_SR830)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_SR830)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_SR830_Y = QtWidgets.QLabel(self.groupBox_SR830)
        self.label_SR830_Y.setText("")
        self.label_SR830_Y.setObjectName("label_SR830_Y")
        self.gridLayout.addWidget(self.label_SR830_Y, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_SR830)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox_SR830)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 1, 0, 1, 1)
        self.label_SR830_R = QtWidgets.QLabel(self.groupBox_SR830)
        self.label_SR830_R.setText("")
        self.label_SR830_R.setObjectName("label_SR830_R")
        self.gridLayout.addWidget(self.label_SR830_R, 2, 1, 1, 1)
        self.label_SR830_X = QtWidgets.QLabel(self.groupBox_SR830)
        self.label_SR830_X.setText("")
        self.label_SR830_X.setObjectName("label_SR830_X")
        self.gridLayout.addWidget(self.label_SR830_X, 0, 1, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.groupBox_SR830)
        self.label_29.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_29.setObjectName("label_29")
        self.gridLayout.addWidget(self.label_29, 4, 0, 1, 1)
        self.label_SR380_RefFreq = QtWidgets.QLabel(self.groupBox_SR830)
        self.label_SR380_RefFreq.setText("")
        self.label_SR380_RefFreq.setObjectName("label_SR380_RefFreq")
        self.gridLayout.addWidget(self.label_SR380_RefFreq, 4, 1, 1, 1)
        self.gridLayout.setColumnStretch(1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.verticalLayout.addWidget(self.groupBox_SR830)
        self.groupBox_AOTF = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_AOTF.setObjectName("groupBox_AOTF")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_AOTF)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.radioButton_AOTF_Fianium = QtWidgets.QRadioButton(self.groupBox_AOTF)
        self.radioButton_AOTF_Fianium.setChecked(True)
        self.radioButton_AOTF_Fianium.setObjectName("radioButton_AOTF_Fianium")
        self.horizontalLayout_18.addWidget(self.radioButton_AOTF_Fianium)
        self.radioButton_AOTF_YSL = QtWidgets.QRadioButton(self.groupBox_AOTF)
        self.radioButton_AOTF_YSL.setObjectName("radioButton_AOTF_YSL")
        self.horizontalLayout_18.addWidget(self.radioButton_AOTF_YSL)
        self.verticalLayout_3.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_AOTF_Conn_Status = QtWidgets.QLabel(self.groupBox_AOTF)
        self.label_AOTF_Conn_Status.setStyleSheet("background: red\n"
"")
        self.label_AOTF_Conn_Status.setText("")
        self.label_AOTF_Conn_Status.setObjectName("label_AOTF_Conn_Status")
        self.horizontalLayout_6.addWidget(self.label_AOTF_Conn_Status)
        self.pushButton_AOTF_Config = QtWidgets.QPushButton(self.groupBox_AOTF)
        self.pushButton_AOTF_Config.setObjectName("pushButton_AOTF_Config")
        self.horizontalLayout_6.addWidget(self.pushButton_AOTF_Config)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_AOTF_Power = QtWidgets.QLabel(self.groupBox_AOTF)
        self.label_AOTF_Power.setText("")
        self.label_AOTF_Power.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_AOTF_Power.setObjectName("label_AOTF_Power")
        self.gridLayout_3.addWidget(self.label_AOTF_Power, 1, 1, 1, 1)
        self.label_AOTF_WaveLength = QtWidgets.QLabel(self.groupBox_AOTF)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_AOTF_WaveLength.sizePolicy().hasHeightForWidth())
        self.label_AOTF_WaveLength.setSizePolicy(sizePolicy)
        self.label_AOTF_WaveLength.setMinimumSize(QtCore.QSize(120, 0))
        self.label_AOTF_WaveLength.setText("")
        self.label_AOTF_WaveLength.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_AOTF_WaveLength.setObjectName("label_AOTF_WaveLength")
        self.gridLayout_3.addWidget(self.label_AOTF_WaveLength, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_AOTF)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 0, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_AOTF)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 1, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_AOTF)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 2, 0, 1, 1)
        self.label_AOTF_PowerPerc = QtWidgets.QLabel(self.groupBox_AOTF)
        self.label_AOTF_PowerPerc.setText("")
        self.label_AOTF_PowerPerc.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_AOTF_PowerPerc.setObjectName("label_AOTF_PowerPerc")
        self.gridLayout_3.addWidget(self.label_AOTF_PowerPerc, 2, 1, 1, 1)
        self.gridLayout_3.setColumnStretch(1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_3)
        self.verticalLayout.addWidget(self.groupBox_AOTF)
        self.groupBox_NIDaq = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_NIDaq.setObjectName("groupBox_NIDaq")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox_NIDaq)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_NIDAQ_Conn_Status = QtWidgets.QLabel(self.groupBox_NIDaq)
        self.label_NIDAQ_Conn_Status.setStyleSheet("background: red\n"
"")
        self.label_NIDAQ_Conn_Status.setText("")
        self.label_NIDAQ_Conn_Status.setObjectName("label_NIDAQ_Conn_Status")
        self.horizontalLayout_9.addWidget(self.label_NIDAQ_Conn_Status)
        self.pushButton_NIDAQ_Config = QtWidgets.QPushButton(self.groupBox_NIDaq)
        self.pushButton_NIDAQ_Config.setObjectName("pushButton_NIDAQ_Config")
        self.horizontalLayout_9.addWidget(self.pushButton_NIDAQ_Config)
        self.verticalLayout_9.addLayout(self.horizontalLayout_9)
        self.verticalLayout.addWidget(self.groupBox_NIDaq)
        self.groupBox_PiezoStage = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_PiezoStage.setObjectName("groupBox_PiezoStage")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.groupBox_PiezoStage)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_Piezo_Conn_Status = QtWidgets.QLabel(self.groupBox_PiezoStage)
        self.label_Piezo_Conn_Status.setStyleSheet("background: red\n"
"")
        self.label_Piezo_Conn_Status.setText("")
        self.label_Piezo_Conn_Status.setObjectName("label_Piezo_Conn_Status")
        self.horizontalLayout_8.addWidget(self.label_Piezo_Conn_Status)
        self.pushButton_Piezo_Config = QtWidgets.QPushButton(self.groupBox_PiezoStage)
        self.pushButton_Piezo_Config.setObjectName("pushButton_Piezo_Config")
        self.horizontalLayout_8.addWidget(self.pushButton_Piezo_Config)
        self.verticalLayout_11.addLayout(self.horizontalLayout_8)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_10 = QtWidgets.QLabel(self.groupBox_PiezoStage)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 2, 0, 1, 1)
        self.label_Piezo_X = QtWidgets.QLabel(self.groupBox_PiezoStage)
        self.label_Piezo_X.setText("")
        self.label_Piezo_X.setObjectName("label_Piezo_X")
        self.gridLayout_4.addWidget(self.label_Piezo_X, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_PiezoStage)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 0, 0, 1, 1)
        self.label_Piezo_Y = QtWidgets.QLabel(self.groupBox_PiezoStage)
        self.label_Piezo_Y.setText("")
        self.label_Piezo_Y.setObjectName("label_Piezo_Y")
        self.gridLayout_4.addWidget(self.label_Piezo_Y, 1, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_PiezoStage)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 1, 0, 1, 1)
        self.label_Piezo_Z = QtWidgets.QLabel(self.groupBox_PiezoStage)
        self.label_Piezo_Z.setText("")
        self.label_Piezo_Z.setObjectName("label_Piezo_Z")
        self.gridLayout_4.addWidget(self.label_Piezo_Z, 2, 1, 1, 1)
        self.verticalLayout_11.addLayout(self.gridLayout_4)
        self.verticalLayout.addWidget(self.groupBox_PiezoStage)
        self.groupBox_Keithley = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_Keithley.setObjectName("groupBox_Keithley")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.groupBox_Keithley)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_Keithley3390_Conn_Status = QtWidgets.QLabel(self.groupBox_Keithley)
        self.label_Keithley3390_Conn_Status.setStyleSheet("background: red\n"
"")
        self.label_Keithley3390_Conn_Status.setText("")
        self.label_Keithley3390_Conn_Status.setObjectName("label_Keithley3390_Conn_Status")
        self.horizontalLayout_16.addWidget(self.label_Keithley3390_Conn_Status)
        self.pushButton_Keithley3390_Config = QtWidgets.QPushButton(self.groupBox_Keithley)
        self.pushButton_Keithley3390_Config.setObjectName("pushButton_Keithley3390_Config")
        self.horizontalLayout_16.addWidget(self.pushButton_Keithley3390_Config)
        self.verticalLayout_14.addLayout(self.horizontalLayout_16)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_35 = QtWidgets.QLabel(self.groupBox_Keithley)
        self.label_35.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_35.setObjectName("label_35")
        self.gridLayout_6.addWidget(self.label_35, 3, 0, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.groupBox_Keithley)
        self.label_32.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_32.setObjectName("label_32")
        self.gridLayout_6.addWidget(self.label_32, 0, 0, 1, 1)
        self.label_Keithley3390_Amp = QtWidgets.QLabel(self.groupBox_Keithley)
        self.label_Keithley3390_Amp.setText("")
        self.label_Keithley3390_Amp.setObjectName("label_Keithley3390_Amp")
        self.gridLayout_6.addWidget(self.label_Keithley3390_Amp, 1, 1, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.groupBox_Keithley)
        self.label_33.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_33.setObjectName("label_33")
        self.gridLayout_6.addWidget(self.label_33, 1, 0, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.groupBox_Keithley)
        self.label_34.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_34.setObjectName("label_34")
        self.gridLayout_6.addWidget(self.label_34, 2, 0, 1, 1)
        self.label_Keithley3390_Freq = QtWidgets.QLabel(self.groupBox_Keithley)
        self.label_Keithley3390_Freq.setText("")
        self.label_Keithley3390_Freq.setObjectName("label_Keithley3390_Freq")
        self.gridLayout_6.addWidget(self.label_Keithley3390_Freq, 0, 1, 1, 1)
        self.label_Keithley3390_Output = QtWidgets.QLabel(self.groupBox_Keithley)
        self.label_Keithley3390_Output.setText("")
        self.label_Keithley3390_Output.setObjectName("label_Keithley3390_Output")
        self.gridLayout_6.addWidget(self.label_Keithley3390_Output, 3, 1, 1, 1)
        self.label_Keithley3390_Offset = QtWidgets.QLabel(self.groupBox_Keithley)
        self.label_Keithley3390_Offset.setText("")
        self.label_Keithley3390_Offset.setObjectName("label_Keithley3390_Offset")
        self.gridLayout_6.addWidget(self.label_Keithley3390_Offset, 2, 1, 1, 1)
        self.verticalLayout_14.addLayout(self.gridLayout_6)
        self.verticalLayout.addWidget(self.groupBox_Keithley)
        self.pushButton_SaveSettings = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_SaveSettings.setObjectName("pushButton_SaveSettings")
        self.verticalLayout.addWidget(self.pushButton_SaveSettings)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.verticalLayout.setStretch(6, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_7.addWidget(self.scrollArea)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_LaserProfiler = QtWidgets.QWidget()
        self.tab_LaserProfiler.setObjectName("tab_LaserProfiler")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_LaserProfiler)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtWidgets.QLabel(self.tab_LaserProfiler)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.comboBox_CamSource = QtWidgets.QComboBox(self.tab_LaserProfiler)
        self.comboBox_CamSource.setMinimumSize(QtCore.QSize(200, 0))
        self.comboBox_CamSource.setObjectName("comboBox_CamSource")
        self.horizontalLayout.addWidget(self.comboBox_CamSource)
        self.label_14 = QtWidgets.QLabel(self.tab_LaserProfiler)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout.addWidget(self.label_14)
        self.comboBox_FrameSelect = QtWidgets.QComboBox(self.tab_LaserProfiler)
        self.comboBox_FrameSelect.setObjectName("comboBox_FrameSelect")
        self.horizontalLayout.addWidget(self.comboBox_FrameSelect)
        self.pushButton_CamRefresh = QtWidgets.QPushButton(self.tab_LaserProfiler)
        self.pushButton_CamRefresh.setObjectName("pushButton_CamRefresh")
        self.horizontalLayout.addWidget(self.pushButton_CamRefresh)
        self.pushButton_CamConn = QtWidgets.QPushButton(self.tab_LaserProfiler)
        self.pushButton_CamConn.setCheckable(True)
        self.pushButton_CamConn.setObjectName("pushButton_CamConn")
        self.horizontalLayout.addWidget(self.pushButton_CamConn)
        self.pushButton_CAM_Config = QtWidgets.QPushButton(self.tab_LaserProfiler)
        self.pushButton_CAM_Config.setEnabled(False)
        self.pushButton_CAM_Config.setObjectName("pushButton_CAM_Config")
        self.horizontalLayout.addWidget(self.pushButton_CAM_Config)
        self.pushButton_FreeRun = QtWidgets.QPushButton(self.tab_LaserProfiler)
        self.pushButton_FreeRun.setEnabled(False)
        self.pushButton_FreeRun.setCheckable(True)
        self.pushButton_FreeRun.setObjectName("pushButton_FreeRun")
        self.horizontalLayout.addWidget(self.pushButton_FreeRun)
        self.pushButton_Single = QtWidgets.QPushButton(self.tab_LaserProfiler)
        self.pushButton_Single.setEnabled(False)
        self.pushButton_Single.setObjectName("pushButton_Single")
        self.horizontalLayout.addWidget(self.pushButton_Single)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pushButton_LP_LoadRaw = QtWidgets.QPushButton(self.tab_LaserProfiler)
        self.pushButton_LP_LoadRaw.setObjectName("pushButton_LP_LoadRaw")
        self.horizontalLayout.addWidget(self.pushButton_LP_LoadRaw)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_15 = QtWidgets.QLabel(self.tab_LaserProfiler)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_10.addWidget(self.label_15)
        self.checkBox_LP_auto_crosshair = QtWidgets.QCheckBox(self.tab_LaserProfiler)
        self.checkBox_LP_auto_crosshair.setObjectName("checkBox_LP_auto_crosshair")
        self.horizontalLayout_10.addWidget(self.checkBox_LP_auto_crosshair)
        self.checkBox_LP_gaussian_force = QtWidgets.QCheckBox(self.tab_LaserProfiler)
        self.checkBox_LP_gaussian_force.setObjectName("checkBox_LP_gaussian_force")
        self.horizontalLayout_10.addWidget(self.checkBox_LP_gaussian_force)
        self.checkBox_LP_gaussian_manual = QtWidgets.QCheckBox(self.tab_LaserProfiler)
        self.checkBox_LP_gaussian_manual.setObjectName("checkBox_LP_gaussian_manual")
        self.horizontalLayout_10.addWidget(self.checkBox_LP_gaussian_manual)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem2)
        self.pushButton_LP_AddMarker = QtWidgets.QPushButton(self.tab_LaserProfiler)
        self.pushButton_LP_AddMarker.setObjectName("pushButton_LP_AddMarker")
        self.horizontalLayout_10.addWidget(self.pushButton_LP_AddMarker)
        self.pushButton_LP_ClearMarkers = QtWidgets.QPushButton(self.tab_LaserProfiler)
        self.pushButton_LP_ClearMarkers.setObjectName("pushButton_LP_ClearMarkers")
        self.horizontalLayout_10.addWidget(self.pushButton_LP_ClearMarkers)
        self.verticalLayout_6.addLayout(self.horizontalLayout_10)
        self.groupBox = QtWidgets.QGroupBox(self.tab_LaserProfiler)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setSpacing(6)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_17 = QtWidgets.QLabel(self.groupBox)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_12.addWidget(self.label_17)
        self.lineEdit_LaserAlignmentFolder = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_LaserAlignmentFolder.sizePolicy().hasHeightForWidth())
        self.lineEdit_LaserAlignmentFolder.setSizePolicy(sizePolicy)
        self.lineEdit_LaserAlignmentFolder.setObjectName("lineEdit_LaserAlignmentFolder")
        self.horizontalLayout_12.addWidget(self.lineEdit_LaserAlignmentFolder)
        self.pushButton_LaserAlignmentFolderSelect = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_LaserAlignmentFolderSelect.setObjectName("pushButton_LaserAlignmentFolderSelect")
        self.horizontalLayout_12.addWidget(self.pushButton_LaserAlignmentFolderSelect)
        self.pushButton_ShowZDistWin = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_ShowZDistWin.setObjectName("pushButton_ShowZDistWin")
        self.horizontalLayout_12.addWidget(self.pushButton_ShowZDistWin)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(6)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout_11.addWidget(self.label)
        self.doubleSpinBox_Z0 = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_Z0.setKeyboardTracking(False)
        self.doubleSpinBox_Z0.setMaximum(200.0)
        self.doubleSpinBox_Z0.setObjectName("doubleSpinBox_Z0")
        self.horizontalLayout_11.addWidget(self.doubleSpinBox_Z0)
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_11.addWidget(self.label_12)
        self.doubleSpinBox_Z1 = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_Z1.setKeyboardTracking(False)
        self.doubleSpinBox_Z1.setMaximum(200.0)
        self.doubleSpinBox_Z1.setObjectName("doubleSpinBox_Z1")
        self.horizontalLayout_11.addWidget(self.doubleSpinBox_Z1)
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_11.addWidget(self.label_13)
        self.doubleSpinBox_Zs = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_Zs.setKeyboardTracking(False)
        self.doubleSpinBox_Zs.setMinimum(0.01)
        self.doubleSpinBox_Zs.setMaximum(100.0)
        self.doubleSpinBox_Zs.setSingleStep(0.01)
        self.doubleSpinBox_Zs.setProperty("value", 0.01)
        self.doubleSpinBox_Zs.setObjectName("doubleSpinBox_Zs")
        self.horizontalLayout_11.addWidget(self.doubleSpinBox_Zs)
        self.pushButton_RunAutoZ = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_RunAutoZ.setObjectName("pushButton_RunAutoZ")
        self.horizontalLayout_11.addWidget(self.pushButton_RunAutoZ)
        self.pushButton_GotoZ0 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_GotoZ0.setObjectName("pushButton_GotoZ0")
        self.horizontalLayout_11.addWidget(self.pushButton_GotoZ0)
        self.pushButton_NextZ = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_NextZ.setObjectName("pushButton_NextZ")
        self.horizontalLayout_11.addWidget(self.pushButton_NextZ)
        self.pushButton_ExportProfile = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_ExportProfile.setObjectName("pushButton_ExportProfile")
        self.horizontalLayout_11.addWidget(self.pushButton_ExportProfile)
        self.label_18 = QtWidgets.QLabel(self.groupBox)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_11.addWidget(self.label_18)
        self.label_LaserAlign_CurrZ = QtWidgets.QLabel(self.groupBox)
        self.label_LaserAlign_CurrZ.setMinimumSize(QtCore.QSize(80, 0))
        self.label_LaserAlign_CurrZ.setText("")
        self.label_LaserAlign_CurrZ.setObjectName("label_LaserAlign_CurrZ")
        self.horizontalLayout_11.addWidget(self.label_LaserAlign_CurrZ)
        self.label_19 = QtWidgets.QLabel(self.groupBox)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_11.addWidget(self.label_19)
        self.label_LaserAlign_HDist = QtWidgets.QLabel(self.groupBox)
        self.label_LaserAlign_HDist.setMinimumSize(QtCore.QSize(80, 0))
        self.label_LaserAlign_HDist.setText("")
        self.label_LaserAlign_HDist.setObjectName("label_LaserAlign_HDist")
        self.horizontalLayout_11.addWidget(self.label_LaserAlign_HDist)
        self.label_20 = QtWidgets.QLabel(self.groupBox)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_11.addWidget(self.label_20)
        self.label_LaserAlign_VDist = QtWidgets.QLabel(self.groupBox)
        self.label_LaserAlign_VDist.setMinimumSize(QtCore.QSize(80, 0))
        self.label_LaserAlign_VDist.setText("")
        self.label_LaserAlign_VDist.setObjectName("label_LaserAlign_VDist")
        self.horizontalLayout_11.addWidget(self.label_LaserAlign_VDist)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        self.verticalLayout_6.addWidget(self.groupBox)
        self.widget_LaserProfiler = LaserProfilerWidget(self.tab_LaserProfiler)
        self.widget_LaserProfiler.setObjectName("widget_LaserProfiler")
        self.verticalLayout_6.addWidget(self.widget_LaserProfiler)
        self.verticalLayout_6.setStretch(3, 1)
        self.tabWidget.addTab(self.tab_LaserProfiler, "")
        self.tab_ZDepthProfile = QtWidgets.QWidget()
        self.tab_ZDepthProfile.setObjectName("tab_ZDepthProfile")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tab_ZDepthProfile)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.pushButton_ExportZDepthProfile = QtWidgets.QPushButton(self.tab_ZDepthProfile)
        self.pushButton_ExportZDepthProfile.setObjectName("pushButton_ExportZDepthProfile")
        self.horizontalLayout_14.addWidget(self.pushButton_ExportZDepthProfile)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem5)
        self.pushButton_ZDepthProfile_LoadRawH = QtWidgets.QPushButton(self.tab_ZDepthProfile)
        self.pushButton_ZDepthProfile_LoadRawH.setObjectName("pushButton_ZDepthProfile_LoadRawH")
        self.horizontalLayout_14.addWidget(self.pushButton_ZDepthProfile_LoadRawH)
        self.pushButton_ZDepthProfile_LoadRawV = QtWidgets.QPushButton(self.tab_ZDepthProfile)
        self.pushButton_ZDepthProfile_LoadRawV.setObjectName("pushButton_ZDepthProfile_LoadRawV")
        self.horizontalLayout_14.addWidget(self.pushButton_ZDepthProfile_LoadRawV)
        self.verticalLayout_8.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widget_ZDepthProfiler_H = LaserProfilerZDepthWidget(self.tab_ZDepthProfile)
        self.widget_ZDepthProfiler_H.setObjectName("widget_ZDepthProfiler_H")
        self.horizontalLayout_3.addWidget(self.widget_ZDepthProfiler_H)
        self.widget_ZDepthProfiler_V = LaserProfilerZDepthWidget(self.tab_ZDepthProfile)
        self.widget_ZDepthProfiler_V.setObjectName("widget_ZDepthProfiler_V")
        self.horizontalLayout_3.addWidget(self.widget_ZDepthProfiler_V)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 1)
        self.verticalLayout_8.addLayout(self.horizontalLayout_3)
        self.verticalLayout_8.setStretch(1, 1)
        self.tabWidget.addTab(self.tab_ZDepthProfile, "")
        self.tab_ViewPhotoDiodeVoltage = QtWidgets.QWidget()
        self.tab_ViewPhotoDiodeVoltage.setObjectName("tab_ViewPhotoDiodeVoltage")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab_ViewPhotoDiodeVoltage)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setSpacing(10)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_21 = QtWidgets.QLabel(self.tab_ViewPhotoDiodeVoltage)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_13.addWidget(self.label_21)
        self.comboBox_PhotoDiode_NIDAQ_Channel = QtWidgets.QComboBox(self.tab_ViewPhotoDiodeVoltage)
        self.comboBox_PhotoDiode_NIDAQ_Channel.setObjectName("comboBox_PhotoDiode_NIDAQ_Channel")
        self.horizontalLayout_13.addWidget(self.comboBox_PhotoDiode_NIDAQ_Channel)
        self.pushButton_PDV_Refresh = QtWidgets.QPushButton(self.tab_ViewPhotoDiodeVoltage)
        self.pushButton_PDV_Refresh.setObjectName("pushButton_PDV_Refresh")
        self.horizontalLayout_13.addWidget(self.pushButton_PDV_Refresh)
        self.pushButton_PDV_AutoRefresh = QtWidgets.QPushButton(self.tab_ViewPhotoDiodeVoltage)
        self.pushButton_PDV_AutoRefresh.setCheckable(True)
        self.pushButton_PDV_AutoRefresh.setObjectName("pushButton_PDV_AutoRefresh")
        self.horizontalLayout_13.addWidget(self.pushButton_PDV_AutoRefresh)
        self.comboBox_PDV_Interval = QtWidgets.QComboBox(self.tab_ViewPhotoDiodeVoltage)
        self.comboBox_PDV_Interval.setInputMethodHints(QtCore.Qt.ImhDate|QtCore.Qt.ImhDigitsOnly)
        self.comboBox_PDV_Interval.setEditable(True)
        self.comboBox_PDV_Interval.setObjectName("comboBox_PDV_Interval")
        self.comboBox_PDV_Interval.addItem("")
        self.comboBox_PDV_Interval.addItem("")
        self.comboBox_PDV_Interval.addItem("")
        self.comboBox_PDV_Interval.addItem("")
        self.comboBox_PDV_Interval.addItem("")
        self.horizontalLayout_13.addWidget(self.comboBox_PDV_Interval)
        self.label_22 = QtWidgets.QLabel(self.tab_ViewPhotoDiodeVoltage)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_13.addWidget(self.label_22)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem6)
        self.verticalLayout_7.addLayout(self.horizontalLayout_13)
        self.widget_PDVPlot = PDVPlotWidget(self.tab_ViewPhotoDiodeVoltage)
        self.widget_PDVPlot.setObjectName("widget_PDVPlot")
        self.verticalLayout_7.addWidget(self.widget_PDVPlot)
        self.verticalLayout_7.setStretch(1, 1)
        self.tabWidget.addTab(self.tab_ViewPhotoDiodeVoltage, "")
        self.tab_LaserCalibration = QtWidgets.QWidget()
        self.tab_LaserCalibration.setObjectName("tab_LaserCalibration")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_LaserCalibration)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.gridLayout_PCaliRun = QtWidgets.QGridLayout()
        self.gridLayout_PCaliRun.setObjectName("gridLayout_PCaliRun")
        self.doubleSpinBox_PCaliPower1Perc = QtWidgets.QDoubleSpinBox(self.tab_LaserCalibration)
        self.doubleSpinBox_PCaliPower1Perc.setDecimals(3)
        self.doubleSpinBox_PCaliPower1Perc.setMaximum(100.0)
        self.doubleSpinBox_PCaliPower1Perc.setProperty("value", 50.0)
        self.doubleSpinBox_PCaliPower1Perc.setObjectName("doubleSpinBox_PCaliPower1Perc")
        self.gridLayout_PCaliRun.addWidget(self.doubleSpinBox_PCaliPower1Perc, 1, 5, 1, 1)
        self.spinBox_PCaliMDelay = QtWidgets.QSpinBox(self.tab_LaserCalibration)
        self.spinBox_PCaliMDelay.setMaximum(5000)
        self.spinBox_PCaliMDelay.setProperty("value", 10)
        self.spinBox_PCaliMDelay.setObjectName("spinBox_PCaliMDelay")
        self.gridLayout_PCaliRun.addWidget(self.spinBox_PCaliMDelay, 2, 9, 1, 1)
        self.label_53 = QtWidgets.QLabel(self.tab_LaserCalibration)
        self.label_53.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_53.setObjectName("label_53")
        self.gridLayout_PCaliRun.addWidget(self.label_53, 2, 0, 1, 2)
        self.lineEdit_PCaliVol = QtWidgets.QLineEdit(self.tab_LaserCalibration)
        self.lineEdit_PCaliVol.setReadOnly(True)
        self.lineEdit_PCaliVol.setObjectName("lineEdit_PCaliVol")
        self.gridLayout_PCaliRun.addWidget(self.lineEdit_PCaliVol, 2, 12, 1, 1)
        self.pushButton_PCaliNextPower = QtWidgets.QPushButton(self.tab_LaserCalibration)
        self.pushButton_PCaliNextPower.setObjectName("pushButton_PCaliNextPower")
        self.gridLayout_PCaliRun.addWidget(self.pushButton_PCaliNextPower, 1, 9, 1, 1)
        self.spinBox_PCaliWLs = QtWidgets.QSpinBox(self.tab_LaserCalibration)
        self.spinBox_PCaliWLs.setKeyboardTracking(False)
        self.spinBox_PCaliWLs.setMinimum(1)
        self.spinBox_PCaliWLs.setMaximum(500)
        self.spinBox_PCaliWLs.setSingleStep(10)
        self.spinBox_PCaliWLs.setProperty("value", 10)
        self.spinBox_PCaliWLs.setObjectName("spinBox_PCaliWLs")
        self.gridLayout_PCaliRun.addWidget(self.spinBox_PCaliWLs, 0, 7, 1, 1)
        self.pushButton_PCaliShowRes = QtWidgets.QPushButton(self.tab_LaserCalibration)
        self.pushButton_PCaliShowRes.setObjectName("pushButton_PCaliShowRes")
        self.gridLayout_PCaliRun.addWidget(self.pushButton_PCaliShowRes, 2, 13, 1, 1)
        self.doubleSpinBox_PCaliMaxVol = QtWidgets.QDoubleSpinBox(self.tab_LaserCalibration)
        self.doubleSpinBox_PCaliMaxVol.setDecimals(4)
        self.doubleSpinBox_PCaliMaxVol.setMaximum(3.6)
        self.doubleSpinBox_PCaliMaxVol.setProperty("value", 3.3)
        self.doubleSpinBox_PCaliMaxVol.setObjectName("doubleSpinBox_PCaliMaxVol")
        self.gridLayout_PCaliRun.addWidget(self.doubleSpinBox_PCaliMaxVol, 2, 7, 1, 1)
        self.comboBox_PCCaliNIDAQCh = QtWidgets.QComboBox(self.tab_LaserCalibration)
        self.comboBox_PCCaliNIDAQCh.setObjectName("comboBox_PCCaliNIDAQCh")
        self.gridLayout_PCaliRun.addWidget(self.comboBox_PCCaliNIDAQCh, 2, 2, 1, 2)
        self.pushButton_PCaliClear = QtWidgets.QPushButton(self.tab_LaserCalibration)
        self.pushButton_PCaliClear.setObjectName("pushButton_PCaliClear")
        self.gridLayout_PCaliRun.addWidget(self.pushButton_PCaliClear, 0, 13, 1, 1)
        self.doubleSpinBox_PCaliPowerSPerc = QtWidgets.QDoubleSpinBox(self.tab_LaserCalibration)
        self.doubleSpinBox_PCaliPowerSPerc.setDecimals(3)
        self.doubleSpinBox_PCaliPowerSPerc.setMinimum(0.001)
        self.doubleSpinBox_PCaliPowerSPerc.setMaximum(100.0)
        self.doubleSpinBox_PCaliPowerSPerc.setProperty("value", 0.01)
        self.doubleSpinBox_PCaliPowerSPerc.setObjectName("doubleSpinBox_PCaliPowerSPerc")
        self.gridLayout_PCaliRun.addWidget(self.doubleSpinBox_PCaliPowerSPerc, 1, 7, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.tab_LaserCalibration)
        self.label_28.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_28.setObjectName("label_28")
        self.gridLayout_PCaliRun.addWidget(self.label_28, 2, 8, 1, 1)
        self.label_52 = QtWidgets.QLabel(self.tab_LaserCalibration)
        self.label_52.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_52.setObjectName("label_52")
        self.gridLayout_PCaliRun.addWidget(self.label_52, 1, 6, 1, 1)
        self.pushButton_PCaliGetVol = QtWidgets.QPushButton(self.tab_LaserCalibration)
        self.pushButton_PCaliGetVol.setObjectName("pushButton_PCaliGetVol")
        self.gridLayout_PCaliRun.addWidget(self.pushButton_PCaliGetVol, 2, 10, 1, 1)
        self.pushButton_PCaliSetWL = QtWidgets.QPushButton(self.tab_LaserCalibration)
        self.pushButton_PCaliSetWL.setObjectName("pushButton_PCaliSetWL")
        self.gridLayout_PCaliRun.addWidget(self.pushButton_PCaliSetWL, 0, 8, 1, 1)
        self.doubleSpinBox_PCaliVolTarget = QtWidgets.QDoubleSpinBox(self.tab_LaserCalibration)
        self.doubleSpinBox_PCaliVolTarget.setDecimals(4)
        self.doubleSpinBox_PCaliVolTarget.setMaximum(12.0)
        self.doubleSpinBox_PCaliVolTarget.setObjectName("doubleSpinBox_PCaliVolTarget")
        self.gridLayout_PCaliRun.addWidget(self.doubleSpinBox_PCaliVolTarget, 2, 5, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.tab_LaserCalibration)
        self.label_24.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName("label_24")
        self.gridLayout_PCaliRun.addWidget(self.label_24, 0, 4, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.tab_LaserCalibration)
        self.label_27.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName("label_27")
        self.gridLayout_PCaliRun.addWidget(self.label_27, 1, 0, 1, 2)
        self.label_55 = QtWidgets.QLabel(self.tab_LaserCalibration)
        self.label_55.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_55.setObjectName("label_55")
        self.gridLayout_PCaliRun.addWidget(self.label_55, 2, 11, 1, 1)
        self.pushButton_PCaliNextWL = QtWidgets.QPushButton(self.tab_LaserCalibration)
        self.pushButton_PCaliNextWL.setObjectName("pushButton_PCaliNextWL")
        self.gridLayout_PCaliRun.addWidget(self.pushButton_PCaliNextWL, 0, 9, 1, 1)
        self.label_51 = QtWidgets.QLabel(self.tab_LaserCalibration)
        self.label_51.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_51.setObjectName("label_51")
        self.gridLayout_PCaliRun.addWidget(self.label_51, 1, 11, 1, 1)
        self.label_54 = QtWidgets.QLabel(self.tab_LaserCalibration)
        self.label_54.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_54.setObjectName("label_54")
        self.gridLayout_PCaliRun.addWidget(self.label_54, 2, 4, 1, 1)
        self.doubleSpinBox_PCaliPower0Perc = QtWidgets.QDoubleSpinBox(self.tab_LaserCalibration)
        self.doubleSpinBox_PCaliPower0Perc.setDecimals(3)
        self.doubleSpinBox_PCaliPower0Perc.setMaximum(100.0)
        self.doubleSpinBox_PCaliPower0Perc.setObjectName("doubleSpinBox_PCaliPower0Perc")
        self.gridLayout_PCaliRun.addWidget(self.doubleSpinBox_PCaliPower0Perc, 1, 2, 1, 2)
        self.label_26 = QtWidgets.QLabel(self.tab_LaserCalibration)
        self.label_26.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName("label_26")
        self.gridLayout_PCaliRun.addWidget(self.label_26, 0, 11, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.tab_LaserCalibration)
        self.label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.gridLayout_PCaliRun.addWidget(self.label_23, 0, 0, 1, 2)
        self.lineEdit_PCaliWLCurr = QtWidgets.QLineEdit(self.tab_LaserCalibration)
        self.lineEdit_PCaliWLCurr.setReadOnly(True)
        self.lineEdit_PCaliWLCurr.setObjectName("lineEdit_PCaliWLCurr")
        self.gridLayout_PCaliRun.addWidget(self.lineEdit_PCaliWLCurr, 0, 12, 1, 1)
        self.spinBox_PCaliWL0 = QtWidgets.QSpinBox(self.tab_LaserCalibration)
        self.spinBox_PCaliWL0.setKeyboardTracking(False)
        self.spinBox_PCaliWL0.setMinimum(400)
        self.spinBox_PCaliWL0.setMaximum(2200)
        self.spinBox_PCaliWL0.setSingleStep(10)
        self.spinBox_PCaliWL0.setObjectName("spinBox_PCaliWL0")
        self.gridLayout_PCaliRun.addWidget(self.spinBox_PCaliWL0, 0, 2, 1, 2)
        self.spinBox_PCaliWL1 = QtWidgets.QSpinBox(self.tab_LaserCalibration)
        self.spinBox_PCaliWL1.setKeyboardTracking(False)
        self.spinBox_PCaliWL1.setMinimum(400)
        self.spinBox_PCaliWL1.setMaximum(2200)
        self.spinBox_PCaliWL1.setSingleStep(10)
        self.spinBox_PCaliWL1.setObjectName("spinBox_PCaliWL1")
        self.gridLayout_PCaliRun.addWidget(self.spinBox_PCaliWL1, 0, 5, 1, 1)
        self.lineEdit_PCaliPowerCurr = QtWidgets.QLineEdit(self.tab_LaserCalibration)
        self.lineEdit_PCaliPowerCurr.setReadOnly(True)
        self.lineEdit_PCaliPowerCurr.setObjectName("lineEdit_PCaliPowerCurr")
        self.gridLayout_PCaliRun.addWidget(self.lineEdit_PCaliPowerCurr, 1, 12, 1, 1)
        self.pushButton_PCaliRun = QtWidgets.QPushButton(self.tab_LaserCalibration)
        self.pushButton_PCaliRun.setObjectName("pushButton_PCaliRun")
        self.gridLayout_PCaliRun.addWidget(self.pushButton_PCaliRun, 1, 13, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.tab_LaserCalibration)
        self.label_25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName("label_25")
        self.gridLayout_PCaliRun.addWidget(self.label_25, 0, 6, 1, 1)
        self.label_57 = QtWidgets.QLabel(self.tab_LaserCalibration)
        self.label_57.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_57.setObjectName("label_57")
        self.gridLayout_PCaliRun.addWidget(self.label_57, 1, 4, 1, 1)
        self.label_66 = QtWidgets.QLabel(self.tab_LaserCalibration)
        self.label_66.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_66.setObjectName("label_66")
        self.gridLayout_PCaliRun.addWidget(self.label_66, 2, 6, 1, 1)
        self.pushButton_PCaliSetPower = QtWidgets.QPushButton(self.tab_LaserCalibration)
        self.pushButton_PCaliSetPower.setObjectName("pushButton_PCaliSetPower")
        self.gridLayout_PCaliRun.addWidget(self.pushButton_PCaliSetPower, 1, 8, 1, 1)
        self.horizontalLayout_20.addLayout(self.gridLayout_PCaliRun)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem7)
        self.horizontalLayout_20.setStretch(1, 1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_20)
        self.widget_PCaliPlot = PCaliPlotWidget(self.tab_LaserCalibration)
        self.widget_PCaliPlot.setObjectName("widget_PCaliPlot")
        self.verticalLayout_4.addWidget(self.widget_PCaliPlot)
        self.verticalLayout_4.setStretch(1, 1)
        self.tabWidget.addTab(self.tab_LaserCalibration, "")
        self.tab_LockInMeasurements = QtWidgets.QWidget()
        self.tab_LockInMeasurements.setObjectName("tab_LockInMeasurements")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.tab_LockInMeasurements)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gridLayout_LIM_Run = QtWidgets.QGridLayout()
        self.gridLayout_LIM_Run.setObjectName("gridLayout_LIM_Run")
        self.label_62 = QtWidgets.QLabel(self.tab_LockInMeasurements)
        self.label_62.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_62.setObjectName("label_62")
        self.gridLayout_LIM_Run.addWidget(self.label_62, 2, 0, 1, 2)
        self.lineEdit_LIM_WLCurr = QtWidgets.QLineEdit(self.tab_LockInMeasurements)
        self.lineEdit_LIM_WLCurr.setReadOnly(True)
        self.lineEdit_LIM_WLCurr.setObjectName("lineEdit_LIM_WLCurr")
        self.gridLayout_LIM_Run.addWidget(self.lineEdit_LIM_WLCurr, 0, 11, 1, 1)
        self.spinBox_LIM_WLs = QtWidgets.QSpinBox(self.tab_LockInMeasurements)
        self.spinBox_LIM_WLs.setKeyboardTracking(False)
        self.spinBox_LIM_WLs.setMinimum(1)
        self.spinBox_LIM_WLs.setMaximum(500)
        self.spinBox_LIM_WLs.setSingleStep(10)
        self.spinBox_LIM_WLs.setProperty("value", 10)
        self.spinBox_LIM_WLs.setObjectName("spinBox_LIM_WLs")
        self.gridLayout_LIM_Run.addWidget(self.spinBox_LIM_WLs, 0, 7, 1, 1)
        self.doubleSpinBox_LIM_PowerPerc = QtWidgets.QDoubleSpinBox(self.tab_LockInMeasurements)
        self.doubleSpinBox_LIM_PowerPerc.setReadOnly(True)
        self.doubleSpinBox_LIM_PowerPerc.setDecimals(3)
        self.doubleSpinBox_LIM_PowerPerc.setMaximum(100.0)
        self.doubleSpinBox_LIM_PowerPerc.setObjectName("doubleSpinBox_LIM_PowerPerc")
        self.gridLayout_LIM_Run.addWidget(self.doubleSpinBox_LIM_PowerPerc, 1, 2, 1, 2)
        self.lineEdit_LIM_Y = QtWidgets.QLineEdit(self.tab_LockInMeasurements)
        self.lineEdit_LIM_Y.setReadOnly(True)
        self.lineEdit_LIM_Y.setObjectName("lineEdit_LIM_Y")
        self.gridLayout_LIM_Run.addWidget(self.lineEdit_LIM_Y, 2, 7, 1, 1)
        self.pushButton_LIM_Measure = QtWidgets.QPushButton(self.tab_LockInMeasurements)
        self.pushButton_LIM_Measure.setObjectName("pushButton_LIM_Measure")
        self.gridLayout_LIM_Run.addWidget(self.pushButton_LIM_Measure, 2, 8, 1, 1)
        self.spinBox_LIM_MeasureDelay = QtWidgets.QSpinBox(self.tab_LockInMeasurements)
        self.spinBox_LIM_MeasureDelay.setKeyboardTracking(False)
        self.spinBox_LIM_MeasureDelay.setMinimum(0)
        self.spinBox_LIM_MeasureDelay.setMaximum(50000)
        self.spinBox_LIM_MeasureDelay.setSingleStep(10)
        self.spinBox_LIM_MeasureDelay.setProperty("value", 10)
        self.spinBox_LIM_MeasureDelay.setObjectName("spinBox_LIM_MeasureDelay")
        self.gridLayout_LIM_Run.addWidget(self.spinBox_LIM_MeasureDelay, 2, 2, 1, 2)
        self.label_60 = QtWidgets.QLabel(self.tab_LockInMeasurements)
        self.label_60.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_60.setObjectName("label_60")
        self.gridLayout_LIM_Run.addWidget(self.label_60, 2, 4, 1, 1)
        self.label_63 = QtWidgets.QLabel(self.tab_LockInMeasurements)
        self.label_63.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_63.setObjectName("label_63")
        self.gridLayout_LIM_Run.addWidget(self.label_63, 2, 6, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.tab_LockInMeasurements)
        self.label_41.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_41.setObjectName("label_41")
        self.gridLayout_LIM_Run.addWidget(self.label_41, 0, 4, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.tab_LockInMeasurements)
        self.label_40.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_40.setObjectName("label_40")
        self.gridLayout_LIM_Run.addWidget(self.label_40, 0, 10, 1, 1)
        self.label_58 = QtWidgets.QLabel(self.tab_LockInMeasurements)
        self.label_58.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_58.setObjectName("label_58")
        self.gridLayout_LIM_Run.addWidget(self.label_58, 1, 0, 1, 2)
        self.pushButton_LIM_ShowResult = QtWidgets.QPushButton(self.tab_LockInMeasurements)
        self.pushButton_LIM_ShowResult.setObjectName("pushButton_LIM_ShowResult")
        self.gridLayout_LIM_Run.addWidget(self.pushButton_LIM_ShowResult, 2, 11, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.tab_LockInMeasurements)
        self.label_39.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_39.setObjectName("label_39")
        self.gridLayout_LIM_Run.addWidget(self.label_39, 0, 0, 1, 2)
        self.pushButton_LIM_LoadCaliPower = QtWidgets.QPushButton(self.tab_LockInMeasurements)
        self.pushButton_LIM_LoadCaliPower.setObjectName("pushButton_LIM_LoadCaliPower")
        self.gridLayout_LIM_Run.addWidget(self.pushButton_LIM_LoadCaliPower, 2, 9, 1, 1)
        self.lineEdit_LIM_X = QtWidgets.QLineEdit(self.tab_LockInMeasurements)
        self.lineEdit_LIM_X.setReadOnly(True)
        self.lineEdit_LIM_X.setObjectName("lineEdit_LIM_X")
        self.gridLayout_LIM_Run.addWidget(self.lineEdit_LIM_X, 2, 5, 1, 1)
        self.spinBox_LIM_WL1 = QtWidgets.QSpinBox(self.tab_LockInMeasurements)
        self.spinBox_LIM_WL1.setKeyboardTracking(False)
        self.spinBox_LIM_WL1.setMinimum(400)
        self.spinBox_LIM_WL1.setMaximum(2200)
        self.spinBox_LIM_WL1.setSingleStep(10)
        self.spinBox_LIM_WL1.setObjectName("spinBox_LIM_WL1")
        self.gridLayout_LIM_Run.addWidget(self.spinBox_LIM_WL1, 0, 5, 1, 1)
        self.label_61 = QtWidgets.QLabel(self.tab_LockInMeasurements)
        self.label_61.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_61.setObjectName("label_61")
        self.gridLayout_LIM_Run.addWidget(self.label_61, 0, 6, 1, 1)
        self.pushButton_LIM_NextWL = QtWidgets.QPushButton(self.tab_LockInMeasurements)
        self.pushButton_LIM_NextWL.setObjectName("pushButton_LIM_NextWL")
        self.gridLayout_LIM_Run.addWidget(self.pushButton_LIM_NextWL, 0, 9, 1, 1)
        self.pushButton_LIM_Auto = QtWidgets.QPushButton(self.tab_LockInMeasurements)
        self.pushButton_LIM_Auto.setObjectName("pushButton_LIM_Auto")
        self.gridLayout_LIM_Run.addWidget(self.pushButton_LIM_Auto, 2, 10, 1, 1)
        self.pushButton_LIM_SetWL0 = QtWidgets.QPushButton(self.tab_LockInMeasurements)
        self.pushButton_LIM_SetWL0.setObjectName("pushButton_LIM_SetWL0")
        self.gridLayout_LIM_Run.addWidget(self.pushButton_LIM_SetWL0, 0, 8, 1, 1)
        self.spinBox_LIM_WL0 = QtWidgets.QSpinBox(self.tab_LockInMeasurements)
        self.spinBox_LIM_WL0.setKeyboardTracking(False)
        self.spinBox_LIM_WL0.setMinimum(400)
        self.spinBox_LIM_WL0.setMaximum(2200)
        self.spinBox_LIM_WL0.setSingleStep(10)
        self.spinBox_LIM_WL0.setObjectName("spinBox_LIM_WL0")
        self.gridLayout_LIM_Run.addWidget(self.spinBox_LIM_WL0, 0, 2, 1, 2)
        self.label_59 = QtWidgets.QLabel(self.tab_LockInMeasurements)
        self.label_59.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_59.setObjectName("label_59")
        self.gridLayout_LIM_Run.addWidget(self.label_59, 1, 4, 1, 1)
        self.doubleSpinBox_LIM_CaliPowerPerc = QtWidgets.QDoubleSpinBox(self.tab_LockInMeasurements)
        self.doubleSpinBox_LIM_CaliPowerPerc.setReadOnly(True)
        self.doubleSpinBox_LIM_CaliPowerPerc.setDecimals(3)
        self.doubleSpinBox_LIM_CaliPowerPerc.setMaximum(100.0)
        self.doubleSpinBox_LIM_CaliPowerPerc.setObjectName("doubleSpinBox_LIM_CaliPowerPerc")
        self.gridLayout_LIM_Run.addWidget(self.doubleSpinBox_LIM_CaliPowerPerc, 1, 5, 1, 1)
        self.pushButton_LIM_SetCaliPower = QtWidgets.QPushButton(self.tab_LockInMeasurements)
        self.pushButton_LIM_SetCaliPower.setObjectName("pushButton_LIM_SetCaliPower")
        self.gridLayout_LIM_Run.addWidget(self.pushButton_LIM_SetCaliPower, 1, 6, 1, 1)
        self.pushButton_LIM_SetPower = QtWidgets.QPushButton(self.tab_LockInMeasurements)
        self.pushButton_LIM_SetPower.setObjectName("pushButton_LIM_SetPower")
        self.gridLayout_LIM_Run.addWidget(self.pushButton_LIM_SetPower, 1, 7, 1, 1)
        self.label_56 = QtWidgets.QLabel(self.tab_LockInMeasurements)
        self.label_56.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_56.setObjectName("label_56")
        self.gridLayout_LIM_Run.addWidget(self.label_56, 1, 8, 1, 1)
        self.lineEdit_LIM_PowerCurr = QtWidgets.QLineEdit(self.tab_LockInMeasurements)
        self.lineEdit_LIM_PowerCurr.setReadOnly(True)
        self.lineEdit_LIM_PowerCurr.setObjectName("lineEdit_LIM_PowerCurr")
        self.gridLayout_LIM_Run.addWidget(self.lineEdit_LIM_PowerCurr, 1, 9, 1, 1)
        self.pushButton_LIM_ClearPlots = QtWidgets.QPushButton(self.tab_LockInMeasurements)
        self.pushButton_LIM_ClearPlots.setObjectName("pushButton_LIM_ClearPlots")
        self.gridLayout_LIM_Run.addWidget(self.pushButton_LIM_ClearPlots, 1, 11, 1, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout_LIM_Run)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem8)
        self.horizontalLayout_4.setStretch(1, 1)
        self.verticalLayout_13.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_LockInPlot = LockInPlotWidget(self.tab_LockInMeasurements)
        self.widget_LockInPlot.setObjectName("widget_LockInPlot")
        self.horizontalLayout_2.addWidget(self.widget_LockInPlot)
        self.verticalLayout_13.addLayout(self.horizontalLayout_2)
        self.verticalLayout_13.setStretch(1, 1)
        self.tabWidget.addTab(self.tab_LockInMeasurements, "")
        self.tab_MapMeasurements = QtWidgets.QWidget()
        self.tab_MapMeasurements.setObjectName("tab_MapMeasurements")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.tab_MapMeasurements)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.gridLayout_MapM_Run = QtWidgets.QGridLayout()
        self.gridLayout_MapM_Run.setObjectName("gridLayout_MapM_Run")
        self.lineEdit_MapM_LockInY = QtWidgets.QLineEdit(self.tab_MapMeasurements)
        self.lineEdit_MapM_LockInY.setReadOnly(True)
        self.lineEdit_MapM_LockInY.setObjectName("lineEdit_MapM_LockInY")
        self.gridLayout_MapM_Run.addWidget(self.lineEdit_MapM_LockInY, 1, 12, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.tab_MapMeasurements)
        self.label_46.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_46.setObjectName("label_46")
        self.gridLayout_MapM_Run.addWidget(self.label_46, 0, 4, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.tab_MapMeasurements)
        self.label_45.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_45.setObjectName("label_45")
        self.gridLayout_MapM_Run.addWidget(self.label_45, 0, 0, 1, 2)
        self.lineEdit_MapM_LockInX = QtWidgets.QLineEdit(self.tab_MapMeasurements)
        self.lineEdit_MapM_LockInX.setReadOnly(True)
        self.lineEdit_MapM_LockInX.setObjectName("lineEdit_MapM_LockInX")
        self.gridLayout_MapM_Run.addWidget(self.lineEdit_MapM_LockInX, 0, 12, 1, 1)
        self.pushButton_MapM_GoY0 = QtWidgets.QPushButton(self.tab_MapMeasurements)
        self.pushButton_MapM_GoY0.setObjectName("pushButton_MapM_GoY0")
        self.gridLayout_MapM_Run.addWidget(self.pushButton_MapM_GoY0, 1, 10, 1, 1)
        self.pushButton_MapM_GoX0 = QtWidgets.QPushButton(self.tab_MapMeasurements)
        self.pushButton_MapM_GoX0.setObjectName("pushButton_MapM_GoX0")
        self.gridLayout_MapM_Run.addWidget(self.pushButton_MapM_GoX0, 0, 10, 1, 1)
        self.lineEdit_MapM_XStep = QtWidgets.QLineEdit(self.tab_MapMeasurements)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_MapM_XStep.sizePolicy().hasHeightForWidth())
        self.lineEdit_MapM_XStep.setSizePolicy(sizePolicy)
        self.lineEdit_MapM_XStep.setMaximumSize(QtCore.QSize(140, 16777215))
        self.lineEdit_MapM_XStep.setReadOnly(True)
        self.lineEdit_MapM_XStep.setObjectName("lineEdit_MapM_XStep")
        self.gridLayout_MapM_Run.addWidget(self.lineEdit_MapM_XStep, 0, 9, 1, 1)
        self.doubleSpinBox_MapM_Y1 = QtWidgets.QDoubleSpinBox(self.tab_MapMeasurements)
        self.doubleSpinBox_MapM_Y1.setKeyboardTracking(False)
        self.doubleSpinBox_MapM_Y1.setDecimals(6)
        self.doubleSpinBox_MapM_Y1.setMaximum(200.0)
        self.doubleSpinBox_MapM_Y1.setSingleStep(0.01)
        self.doubleSpinBox_MapM_Y1.setObjectName("doubleSpinBox_MapM_Y1")
        self.gridLayout_MapM_Run.addWidget(self.doubleSpinBox_MapM_Y1, 1, 5, 1, 1)
        self.label_72 = QtWidgets.QLabel(self.tab_MapMeasurements)
        self.label_72.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_72.setObjectName("label_72")
        self.gridLayout_MapM_Run.addWidget(self.label_72, 0, 11, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.tab_MapMeasurements)
        self.label_44.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_44.setObjectName("label_44")
        self.gridLayout_MapM_Run.addWidget(self.label_44, 1, 0, 1, 2)
        self.label_73 = QtWidgets.QLabel(self.tab_MapMeasurements)
        self.label_73.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_73.setObjectName("label_73")
        self.gridLayout_MapM_Run.addWidget(self.label_73, 1, 11, 1, 1)
        self.label_69 = QtWidgets.QLabel(self.tab_MapMeasurements)
        self.label_69.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_69.setObjectName("label_69")
        self.gridLayout_MapM_Run.addWidget(self.label_69, 1, 6, 1, 1)
        self.label_68 = QtWidgets.QLabel(self.tab_MapMeasurements)
        self.label_68.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_68.setObjectName("label_68")
        self.gridLayout_MapM_Run.addWidget(self.label_68, 0, 6, 1, 1)
        self.lineEdit_MapM_YStep = QtWidgets.QLineEdit(self.tab_MapMeasurements)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_MapM_YStep.sizePolicy().hasHeightForWidth())
        self.lineEdit_MapM_YStep.setSizePolicy(sizePolicy)
        self.lineEdit_MapM_YStep.setMaximumSize(QtCore.QSize(140, 16777215))
        self.lineEdit_MapM_YStep.setReadOnly(True)
        self.lineEdit_MapM_YStep.setObjectName("lineEdit_MapM_YStep")
        self.gridLayout_MapM_Run.addWidget(self.lineEdit_MapM_YStep, 1, 9, 1, 1)
        self.doubleSpinBox_MapM_X0 = QtWidgets.QDoubleSpinBox(self.tab_MapMeasurements)
        self.doubleSpinBox_MapM_X0.setKeyboardTracking(False)
        self.doubleSpinBox_MapM_X0.setDecimals(6)
        self.doubleSpinBox_MapM_X0.setMaximum(200.0)
        self.doubleSpinBox_MapM_X0.setSingleStep(0.01)
        self.doubleSpinBox_MapM_X0.setObjectName("doubleSpinBox_MapM_X0")
        self.gridLayout_MapM_Run.addWidget(self.doubleSpinBox_MapM_X0, 0, 2, 1, 2)
        self.label_70 = QtWidgets.QLabel(self.tab_MapMeasurements)
        self.label_70.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_70.setObjectName("label_70")
        self.gridLayout_MapM_Run.addWidget(self.label_70, 0, 8, 1, 1)
        self.label_71 = QtWidgets.QLabel(self.tab_MapMeasurements)
        self.label_71.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_71.setObjectName("label_71")
        self.gridLayout_MapM_Run.addWidget(self.label_71, 1, 8, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.tab_MapMeasurements)
        self.label_47.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_47.setObjectName("label_47")
        self.gridLayout_MapM_Run.addWidget(self.label_47, 1, 4, 1, 1)
        self.spinBox_MapM_XSamples = QtWidgets.QSpinBox(self.tab_MapMeasurements)
        self.spinBox_MapM_XSamples.setKeyboardTracking(False)
        self.spinBox_MapM_XSamples.setMinimum(2)
        self.spinBox_MapM_XSamples.setMaximum(201)
        self.spinBox_MapM_XSamples.setSingleStep(1)
        self.spinBox_MapM_XSamples.setProperty("value", 11)
        self.spinBox_MapM_XSamples.setObjectName("spinBox_MapM_XSamples")
        self.gridLayout_MapM_Run.addWidget(self.spinBox_MapM_XSamples, 0, 7, 1, 1)
        self.doubleSpinBox_MapM_X1 = QtWidgets.QDoubleSpinBox(self.tab_MapMeasurements)
        self.doubleSpinBox_MapM_X1.setKeyboardTracking(False)
        self.doubleSpinBox_MapM_X1.setDecimals(6)
        self.doubleSpinBox_MapM_X1.setMaximum(200.0)
        self.doubleSpinBox_MapM_X1.setSingleStep(0.01)
        self.doubleSpinBox_MapM_X1.setObjectName("doubleSpinBox_MapM_X1")
        self.gridLayout_MapM_Run.addWidget(self.doubleSpinBox_MapM_X1, 0, 5, 1, 1)
        self.spinBox_MapM_YSamples = QtWidgets.QSpinBox(self.tab_MapMeasurements)
        self.spinBox_MapM_YSamples.setKeyboardTracking(False)
        self.spinBox_MapM_YSamples.setMinimum(2)
        self.spinBox_MapM_YSamples.setMaximum(201)
        self.spinBox_MapM_YSamples.setSingleStep(1)
        self.spinBox_MapM_YSamples.setProperty("value", 11)
        self.spinBox_MapM_YSamples.setObjectName("spinBox_MapM_YSamples")
        self.gridLayout_MapM_Run.addWidget(self.spinBox_MapM_YSamples, 1, 7, 1, 1)
        self.doubleSpinBox_MapM_Y0 = QtWidgets.QDoubleSpinBox(self.tab_MapMeasurements)
        self.doubleSpinBox_MapM_Y0.setKeyboardTracking(False)
        self.doubleSpinBox_MapM_Y0.setDecimals(6)
        self.doubleSpinBox_MapM_Y0.setMaximum(200.0)
        self.doubleSpinBox_MapM_Y0.setSingleStep(0.01)
        self.doubleSpinBox_MapM_Y0.setObjectName("doubleSpinBox_MapM_Y0")
        self.gridLayout_MapM_Run.addWidget(self.doubleSpinBox_MapM_Y0, 1, 2, 1, 2)
        self.horizontalLayout_17.addLayout(self.gridLayout_MapM_Run)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem9)
        self.verticalLayout_10.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_48 = QtWidgets.QLabel(self.tab_MapMeasurements)
        self.label_48.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_48.setObjectName("label_48")
        self.horizontalLayout_15.addWidget(self.label_48)
        self.label_Mapm_SigGenOutput = QtWidgets.QLabel(self.tab_MapMeasurements)
        self.label_Mapm_SigGenOutput.setMinimumSize(QtCore.QSize(80, 0))
        self.label_Mapm_SigGenOutput.setText("")
        self.label_Mapm_SigGenOutput.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Mapm_SigGenOutput.setObjectName("label_Mapm_SigGenOutput")
        self.horizontalLayout_15.addWidget(self.label_Mapm_SigGenOutput)
        self.label_64 = QtWidgets.QLabel(self.tab_MapMeasurements)
        self.label_64.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_64.setObjectName("label_64")
        self.horizontalLayout_15.addWidget(self.label_64)
        self.comboBox_MapM_NIDAQCh = QtWidgets.QComboBox(self.tab_MapMeasurements)
        self.comboBox_MapM_NIDAQCh.setObjectName("comboBox_MapM_NIDAQCh")
        self.horizontalLayout_15.addWidget(self.comboBox_MapM_NIDAQCh)
        self.lineEdit_MapM_NiVol = QtWidgets.QLineEdit(self.tab_MapMeasurements)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_MapM_NiVol.sizePolicy().hasHeightForWidth())
        self.lineEdit_MapM_NiVol.setSizePolicy(sizePolicy)
        self.lineEdit_MapM_NiVol.setMaximumSize(QtCore.QSize(160, 16777215))
        self.lineEdit_MapM_NiVol.setReadOnly(True)
        self.lineEdit_MapM_NiVol.setObjectName("lineEdit_MapM_NiVol")
        self.horizontalLayout_15.addWidget(self.lineEdit_MapM_NiVol)
        self.label_65 = QtWidgets.QLabel(self.tab_MapMeasurements)
        self.label_65.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_65.setObjectName("label_65")
        self.horizontalLayout_15.addWidget(self.label_65)
        self.spinBox_MapM_MeasureDelay = QtWidgets.QSpinBox(self.tab_MapMeasurements)
        self.spinBox_MapM_MeasureDelay.setKeyboardTracking(False)
        self.spinBox_MapM_MeasureDelay.setMinimum(10)
        self.spinBox_MapM_MeasureDelay.setMaximum(50000)
        self.spinBox_MapM_MeasureDelay.setSingleStep(100)
        self.spinBox_MapM_MeasureDelay.setProperty("value", 1000)
        self.spinBox_MapM_MeasureDelay.setObjectName("spinBox_MapM_MeasureDelay")
        self.horizontalLayout_15.addWidget(self.spinBox_MapM_MeasureDelay)
        self.pushButton_MapM_Measure = QtWidgets.QPushButton(self.tab_MapMeasurements)
        self.pushButton_MapM_Measure.setObjectName("pushButton_MapM_Measure")
        self.horizontalLayout_15.addWidget(self.pushButton_MapM_Measure)
        self.pushButton_MapM_Auto = QtWidgets.QPushButton(self.tab_MapMeasurements)
        self.pushButton_MapM_Auto.setObjectName("pushButton_MapM_Auto")
        self.horizontalLayout_15.addWidget(self.pushButton_MapM_Auto)
        spacerItem10 = QtWidgets.QSpacerItem(15, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem10)
        self.pushButton_MapM_Export = QtWidgets.QPushButton(self.tab_MapMeasurements)
        self.pushButton_MapM_Export.setObjectName("pushButton_MapM_Export")
        self.horizontalLayout_15.addWidget(self.pushButton_MapM_Export)
        self.pushButton_MapM_Load = QtWidgets.QPushButton(self.tab_MapMeasurements)
        self.pushButton_MapM_Load.setObjectName("pushButton_MapM_Load")
        self.horizontalLayout_15.addWidget(self.pushButton_MapM_Load)
        self.verticalLayout_10.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.widget_MeasurementPlot1 = MeasurementPlotWidget(self.tab_MapMeasurements)
        self.widget_MeasurementPlot1.setObjectName("widget_MeasurementPlot1")
        self.horizontalLayout_21.addWidget(self.widget_MeasurementPlot1)
        self.widget_MeasurementPlot2 = MeasurementPlotWidget(self.tab_MapMeasurements)
        self.widget_MeasurementPlot2.setMinimumSize(QtCore.QSize(400, 0))
        self.widget_MeasurementPlot2.setObjectName("widget_MeasurementPlot2")
        self.horizontalLayout_21.addWidget(self.widget_MeasurementPlot2)
        self.widget_MeasurementPlot3 = MeasurementPlotWidget(self.tab_MapMeasurements)
        self.widget_MeasurementPlot3.setObjectName("widget_MeasurementPlot3")
        self.horizontalLayout_21.addWidget(self.widget_MeasurementPlot3)
        self.horizontalLayout_21.setStretch(0, 1)
        self.horizontalLayout_21.setStretch(1, 1)
        self.horizontalLayout_21.setStretch(2, 1)
        self.verticalLayout_10.addLayout(self.horizontalLayout_21)
        self.verticalLayout_10.setStretch(2, 1)
        self.tabWidget.addTab(self.tab_MapMeasurements, "")
        self.horizontalLayout_7.addWidget(self.tabWidget)
        self.verticalLayout_16.addLayout(self.horizontalLayout_7)
        SetupMainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(SetupMainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.comboBox_PDV_Interval.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(SetupMainWindow)
        SetupMainWindow.setTabOrder(self.pushButton_SR830_Config, self.pushButton_AOTF_Config)
        SetupMainWindow.setTabOrder(self.pushButton_AOTF_Config, self.pushButton_NIDAQ_Config)
        SetupMainWindow.setTabOrder(self.pushButton_NIDAQ_Config, self.pushButton_Piezo_Config)
        SetupMainWindow.setTabOrder(self.pushButton_Piezo_Config, self.pushButton_Keithley3390_Config)
        SetupMainWindow.setTabOrder(self.pushButton_Keithley3390_Config, self.tabWidget)
        SetupMainWindow.setTabOrder(self.tabWidget, self.comboBox_CamSource)
        SetupMainWindow.setTabOrder(self.comboBox_CamSource, self.comboBox_FrameSelect)
        SetupMainWindow.setTabOrder(self.comboBox_FrameSelect, self.pushButton_CamRefresh)
        SetupMainWindow.setTabOrder(self.pushButton_CamRefresh, self.pushButton_CamConn)
        SetupMainWindow.setTabOrder(self.pushButton_CamConn, self.pushButton_CAM_Config)
        SetupMainWindow.setTabOrder(self.pushButton_CAM_Config, self.pushButton_FreeRun)
        SetupMainWindow.setTabOrder(self.pushButton_FreeRun, self.pushButton_Single)
        SetupMainWindow.setTabOrder(self.pushButton_Single, self.checkBox_LP_auto_crosshair)
        SetupMainWindow.setTabOrder(self.checkBox_LP_auto_crosshair, self.checkBox_LP_gaussian_force)
        SetupMainWindow.setTabOrder(self.checkBox_LP_gaussian_force, self.checkBox_LP_gaussian_manual)
        SetupMainWindow.setTabOrder(self.checkBox_LP_gaussian_manual, self.lineEdit_LaserAlignmentFolder)
        SetupMainWindow.setTabOrder(self.lineEdit_LaserAlignmentFolder, self.pushButton_LaserAlignmentFolderSelect)
        SetupMainWindow.setTabOrder(self.pushButton_LaserAlignmentFolderSelect, self.pushButton_ShowZDistWin)
        SetupMainWindow.setTabOrder(self.pushButton_ShowZDistWin, self.doubleSpinBox_Z0)
        SetupMainWindow.setTabOrder(self.doubleSpinBox_Z0, self.doubleSpinBox_Z1)
        SetupMainWindow.setTabOrder(self.doubleSpinBox_Z1, self.doubleSpinBox_Zs)
        SetupMainWindow.setTabOrder(self.doubleSpinBox_Zs, self.pushButton_RunAutoZ)
        SetupMainWindow.setTabOrder(self.pushButton_RunAutoZ, self.pushButton_GotoZ0)
        SetupMainWindow.setTabOrder(self.pushButton_GotoZ0, self.pushButton_NextZ)
        SetupMainWindow.setTabOrder(self.pushButton_NextZ, self.pushButton_ExportProfile)
        SetupMainWindow.setTabOrder(self.pushButton_ExportProfile, self.pushButton_LP_LoadRaw)
        SetupMainWindow.setTabOrder(self.pushButton_LP_LoadRaw, self.pushButton_ExportZDepthProfile)
        SetupMainWindow.setTabOrder(self.pushButton_ExportZDepthProfile, self.pushButton_ZDepthProfile_LoadRawH)
        SetupMainWindow.setTabOrder(self.pushButton_ZDepthProfile_LoadRawH, self.pushButton_ZDepthProfile_LoadRawV)
        SetupMainWindow.setTabOrder(self.pushButton_ZDepthProfile_LoadRawV, self.comboBox_PhotoDiode_NIDAQ_Channel)
        SetupMainWindow.setTabOrder(self.comboBox_PhotoDiode_NIDAQ_Channel, self.pushButton_PDV_Refresh)
        SetupMainWindow.setTabOrder(self.pushButton_PDV_Refresh, self.pushButton_PDV_AutoRefresh)
        SetupMainWindow.setTabOrder(self.pushButton_PDV_AutoRefresh, self.comboBox_PDV_Interval)
        SetupMainWindow.setTabOrder(self.comboBox_PDV_Interval, self.spinBox_PCaliWL0)
        SetupMainWindow.setTabOrder(self.spinBox_PCaliWL0, self.spinBox_PCaliWL1)
        SetupMainWindow.setTabOrder(self.spinBox_PCaliWL1, self.lineEdit_PCaliWLCurr)
        SetupMainWindow.setTabOrder(self.lineEdit_PCaliWLCurr, self.doubleSpinBox_PCaliPower0Perc)
        SetupMainWindow.setTabOrder(self.doubleSpinBox_PCaliPower0Perc, self.doubleSpinBox_PCaliPower1Perc)
        SetupMainWindow.setTabOrder(self.doubleSpinBox_PCaliPower1Perc, self.lineEdit_PCaliPowerCurr)
        SetupMainWindow.setTabOrder(self.lineEdit_PCaliPowerCurr, self.comboBox_PCCaliNIDAQCh)
        SetupMainWindow.setTabOrder(self.comboBox_PCCaliNIDAQCh, self.doubleSpinBox_PCaliVolTarget)
        SetupMainWindow.setTabOrder(self.doubleSpinBox_PCaliVolTarget, self.spinBox_PCaliMDelay)
        SetupMainWindow.setTabOrder(self.spinBox_PCaliMDelay, self.pushButton_PCaliGetVol)
        SetupMainWindow.setTabOrder(self.pushButton_PCaliGetVol, self.lineEdit_PCaliVol)
        SetupMainWindow.setTabOrder(self.lineEdit_PCaliVol, self.pushButton_PCaliClear)
        SetupMainWindow.setTabOrder(self.pushButton_PCaliClear, self.pushButton_PCaliRun)
        SetupMainWindow.setTabOrder(self.pushButton_PCaliRun, self.pushButton_PCaliShowRes)
        SetupMainWindow.setTabOrder(self.pushButton_PCaliShowRes, self.spinBox_LIM_WL0)
        SetupMainWindow.setTabOrder(self.spinBox_LIM_WL0, self.spinBox_LIM_WL1)
        SetupMainWindow.setTabOrder(self.spinBox_LIM_WL1, self.spinBox_LIM_WLs)
        SetupMainWindow.setTabOrder(self.spinBox_LIM_WLs, self.pushButton_LIM_SetWL0)
        SetupMainWindow.setTabOrder(self.pushButton_LIM_SetWL0, self.pushButton_LIM_NextWL)
        SetupMainWindow.setTabOrder(self.pushButton_LIM_NextWL, self.lineEdit_LIM_WLCurr)
        SetupMainWindow.setTabOrder(self.lineEdit_LIM_WLCurr, self.doubleSpinBox_LIM_PowerPerc)
        SetupMainWindow.setTabOrder(self.doubleSpinBox_LIM_PowerPerc, self.doubleSpinBox_LIM_CaliPowerPerc)
        SetupMainWindow.setTabOrder(self.doubleSpinBox_LIM_CaliPowerPerc, self.pushButton_LIM_SetCaliPower)
        SetupMainWindow.setTabOrder(self.pushButton_LIM_SetCaliPower, self.pushButton_LIM_SetPower)
        SetupMainWindow.setTabOrder(self.pushButton_LIM_SetPower, self.lineEdit_LIM_PowerCurr)
        SetupMainWindow.setTabOrder(self.lineEdit_LIM_PowerCurr, self.spinBox_LIM_MeasureDelay)
        SetupMainWindow.setTabOrder(self.spinBox_LIM_MeasureDelay, self.lineEdit_LIM_X)
        SetupMainWindow.setTabOrder(self.lineEdit_LIM_X, self.lineEdit_LIM_Y)
        SetupMainWindow.setTabOrder(self.lineEdit_LIM_Y, self.pushButton_LIM_Measure)
        SetupMainWindow.setTabOrder(self.pushButton_LIM_Measure, self.pushButton_LIM_LoadCaliPower)
        SetupMainWindow.setTabOrder(self.pushButton_LIM_LoadCaliPower, self.pushButton_LIM_Auto)
        SetupMainWindow.setTabOrder(self.pushButton_LIM_Auto, self.pushButton_LIM_ShowResult)
        SetupMainWindow.setTabOrder(self.pushButton_LIM_ShowResult, self.pushButton_LIM_ClearPlots)
        SetupMainWindow.setTabOrder(self.pushButton_LIM_ClearPlots, self.doubleSpinBox_MapM_X0)
        SetupMainWindow.setTabOrder(self.doubleSpinBox_MapM_X0, self.doubleSpinBox_MapM_X1)
        SetupMainWindow.setTabOrder(self.doubleSpinBox_MapM_X1, self.spinBox_MapM_XSamples)
        SetupMainWindow.setTabOrder(self.spinBox_MapM_XSamples, self.lineEdit_MapM_XStep)
        SetupMainWindow.setTabOrder(self.lineEdit_MapM_XStep, self.pushButton_MapM_GoX0)
        SetupMainWindow.setTabOrder(self.pushButton_MapM_GoX0, self.doubleSpinBox_MapM_Y0)
        SetupMainWindow.setTabOrder(self.doubleSpinBox_MapM_Y0, self.doubleSpinBox_MapM_Y1)
        SetupMainWindow.setTabOrder(self.doubleSpinBox_MapM_Y1, self.spinBox_MapM_YSamples)
        SetupMainWindow.setTabOrder(self.spinBox_MapM_YSamples, self.lineEdit_MapM_YStep)
        SetupMainWindow.setTabOrder(self.lineEdit_MapM_YStep, self.pushButton_MapM_GoY0)
        SetupMainWindow.setTabOrder(self.pushButton_MapM_GoY0, self.comboBox_MapM_NIDAQCh)
        SetupMainWindow.setTabOrder(self.comboBox_MapM_NIDAQCh, self.lineEdit_MapM_NiVol)
        SetupMainWindow.setTabOrder(self.lineEdit_MapM_NiVol, self.spinBox_MapM_MeasureDelay)
        SetupMainWindow.setTabOrder(self.spinBox_MapM_MeasureDelay, self.pushButton_MapM_Measure)
        SetupMainWindow.setTabOrder(self.pushButton_MapM_Measure, self.pushButton_MapM_Auto)
        SetupMainWindow.setTabOrder(self.pushButton_MapM_Auto, self.lineEdit_MapM_LockInX)
        SetupMainWindow.setTabOrder(self.lineEdit_MapM_LockInX, self.lineEdit_MapM_LockInY)
        SetupMainWindow.setTabOrder(self.lineEdit_MapM_LockInY, self.pushButton_MapM_Export)
        SetupMainWindow.setTabOrder(self.pushButton_MapM_Export, self.pushButton_MapM_Load)
        SetupMainWindow.setTabOrder(self.pushButton_MapM_Load, self.scrollArea)

    def retranslateUi(self, SetupMainWindow):
        _translate = QtCore.QCoreApplication.translate
        SetupMainWindow.setWindowTitle(_translate("SetupMainWindow", "Setup Main Control"))
        self.groupBox_SR830.setTitle(_translate("SetupMainWindow", "SR830"))
        self.pushButton_SR830_Config.setText(_translate("SetupMainWindow", "Config"))
        self.label_4.setText(_translate("SetupMainWindow", "Theta:"))
        self.label_3.setText(_translate("SetupMainWindow", "R:"))
        self.label_2.setText(_translate("SetupMainWindow", "X:"))
        self.label_16.setText(_translate("SetupMainWindow", "Y:"))
        self.label_29.setText(_translate("SetupMainWindow", "F:"))
        self.groupBox_AOTF.setTitle(_translate("SetupMainWindow", "AOTF"))
        self.radioButton_AOTF_Fianium.setText(_translate("SetupMainWindow", "Fianium"))
        self.radioButton_AOTF_YSL.setText(_translate("SetupMainWindow", "&YSL"))
        self.pushButton_AOTF_Config.setText(_translate("SetupMainWindow", "Config"))
        self.label_6.setText(_translate("SetupMainWindow", "Wave L.:"))
        self.label_7.setText(_translate("SetupMainWindow", "Power:"))
        self.label_11.setText(_translate("SetupMainWindow", "Power%:"))
        self.groupBox_NIDaq.setTitle(_translate("SetupMainWindow", "NI DAQ"))
        self.pushButton_NIDAQ_Config.setText(_translate("SetupMainWindow", "Config"))
        self.groupBox_PiezoStage.setTitle(_translate("SetupMainWindow", "Piezo Micro Stage"))
        self.pushButton_Piezo_Config.setText(_translate("SetupMainWindow", "Config"))
        self.label_10.setText(_translate("SetupMainWindow", "Z:"))
        self.label_8.setText(_translate("SetupMainWindow", "X:"))
        self.label_9.setText(_translate("SetupMainWindow", "Y:"))
        self.groupBox_Keithley.setTitle(_translate("SetupMainWindow", "Keithley 3390"))
        self.pushButton_Keithley3390_Config.setText(_translate("SetupMainWindow", "Config"))
        self.label_35.setText(_translate("SetupMainWindow", "OUTPUT:"))
        self.label_32.setText(_translate("SetupMainWindow", "Frequency:"))
        self.label_33.setText(_translate("SetupMainWindow", "Amplitude:"))
        self.label_34.setText(_translate("SetupMainWindow", "Offset:"))
        self.pushButton_SaveSettings.setText(_translate("SetupMainWindow", "Save Settings ..."))
        self.label_5.setText(_translate("SetupMainWindow", "Source:"))
        self.label_14.setText(_translate("SetupMainWindow", "Frame Select:"))
        self.pushButton_CamRefresh.setText(_translate("SetupMainWindow", "Refresh"))
        self.pushButton_CamConn.setText(_translate("SetupMainWindow", "Connect"))
        self.pushButton_CAM_Config.setText(_translate("SetupMainWindow", "Configure"))
        self.pushButton_FreeRun.setText(_translate("SetupMainWindow", "Free Run"))
        self.pushButton_Single.setText(_translate("SetupMainWindow", "Single Frame"))
        self.pushButton_LP_LoadRaw.setText(_translate("SetupMainWindow", "Load Raw"))
        self.label_15.setText(_translate("SetupMainWindow", "Options:"))
        self.checkBox_LP_auto_crosshair.setText(_translate("SetupMainWindow", "Cross Hair Auto Hotspot"))
        self.checkBox_LP_gaussian_force.setText(_translate("SetupMainWindow", "Gaussian Fit Force Peak"))
        self.checkBox_LP_gaussian_manual.setText(_translate("SetupMainWindow", "Gaussian Fit Manual Mean"))
        self.pushButton_LP_AddMarker.setText(_translate("SetupMainWindow", "Add Marker"))
        self.pushButton_LP_ClearMarkers.setText(_translate("SetupMainWindow", "Clear Markers"))
        self.groupBox.setTitle(_translate("SetupMainWindow", "Alignment Run"))
        self.label_17.setText(_translate("SetupMainWindow", "Run Folder:"))
        self.lineEdit_LaserAlignmentFolder.setText(_translate("SetupMainWindow", "."))
        self.pushButton_LaserAlignmentFolderSelect.setText(_translate("SetupMainWindow", "Select Folder"))
        self.pushButton_ShowZDistWin.setText(_translate("SetupMainWindow", "Show Z Dists"))
        self.label.setText(_translate("SetupMainWindow", "Z0"))
        self.label_12.setText(_translate("SetupMainWindow", "Z1"))
        self.label_13.setText(_translate("SetupMainWindow", "Zs"))
        self.pushButton_RunAutoZ.setToolTip(_translate("SetupMainWindow", "Require AOTF, PZT, Camera"))
        self.pushButton_RunAutoZ.setText(_translate("SetupMainWindow", "AutoZ"))
        self.pushButton_GotoZ0.setText(_translate("SetupMainWindow", "Go to Z0"))
        self.pushButton_NextZ.setText(_translate("SetupMainWindow", "Next Z"))
        self.pushButton_ExportProfile.setText(_translate("SetupMainWindow", "Export"))
        self.label_18.setText(_translate("SetupMainWindow", "Z:"))
        self.label_19.setText(_translate("SetupMainWindow", "H:"))
        self.label_20.setText(_translate("SetupMainWindow", "V:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_LaserProfiler), _translate("SetupMainWindow", "Laser Alignment"))
        self.pushButton_ExportZDepthProfile.setText(_translate("SetupMainWindow", "Export"))
        self.pushButton_ZDepthProfile_LoadRawH.setText(_translate("SetupMainWindow", "Load Raw H"))
        self.pushButton_ZDepthProfile_LoadRawV.setText(_translate("SetupMainWindow", "Load Raw V"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_ZDepthProfile), _translate("SetupMainWindow", "Z Depth Profile"))
        self.label_21.setText(_translate("SetupMainWindow", "NI DAQ Channel:"))
        self.pushButton_PDV_Refresh.setText(_translate("SetupMainWindow", "Update"))
        self.pushButton_PDV_AutoRefresh.setText(_translate("SetupMainWindow", "Auto Refresh"))
        self.comboBox_PDV_Interval.setItemText(0, _translate("SetupMainWindow", "0"))
        self.comboBox_PDV_Interval.setItemText(1, _translate("SetupMainWindow", "10"))
        self.comboBox_PDV_Interval.setItemText(2, _translate("SetupMainWindow", "100"))
        self.comboBox_PDV_Interval.setItemText(3, _translate("SetupMainWindow", "1000"))
        self.comboBox_PDV_Interval.setItemText(4, _translate("SetupMainWindow", "3000"))
        self.label_22.setText(_translate("SetupMainWindow", "ms"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_ViewPhotoDiodeVoltage), _translate("SetupMainWindow", "Photo Diode Voltage"))
        self.spinBox_PCaliMDelay.setToolTip(_translate("SetupMainWindow", "millisecond"))
        self.label_53.setText(_translate("SetupMainWindow", "NIDAQ Ch:"))
        self.pushButton_PCaliNextPower.setText(_translate("SetupMainWindow", "Next Power"))
        self.pushButton_PCaliShowRes.setText(_translate("SetupMainWindow", "Show Result"))
        self.pushButton_PCaliClear.setText(_translate("SetupMainWindow", "Clear Plots"))
        self.label_28.setToolTip(_translate("SetupMainWindow", "Measurement Delay"))
        self.label_28.setText(_translate("SetupMainWindow", "M. Delay"))
        self.label_52.setText(_translate("SetupMainWindow", "Power.s:"))
        self.pushButton_PCaliGetVol.setText(_translate("SetupMainWindow", "Get Voltage"))
        self.pushButton_PCaliSetWL.setText(_translate("SetupMainWindow", "Set WL0"))
        self.label_24.setText(_translate("SetupMainWindow", "WL1:"))
        self.label_27.setText(_translate("SetupMainWindow", "Power0%:"))
        self.label_55.setText(_translate("SetupMainWindow", "Vol:"))
        self.pushButton_PCaliNextWL.setText(_translate("SetupMainWindow", "Next WL"))
        self.label_51.setText(_translate("SetupMainWindow", "Power:"))
        self.label_54.setToolTip(_translate("SetupMainWindow", "Target Voltage:"))
        self.label_54.setText(_translate("SetupMainWindow", "T Vol:"))
        self.label_26.setText(_translate("SetupMainWindow", "WL:"))
        self.label_23.setText(_translate("SetupMainWindow", "WL0:"))
        self.pushButton_PCaliRun.setText(_translate("SetupMainWindow", "Run Cali"))
        self.label_25.setText(_translate("SetupMainWindow", "WLs:"))
        self.label_57.setText(_translate("SetupMainWindow", "Power1%:"))
        self.label_66.setText(_translate("SetupMainWindow", "Max V:"))
        self.pushButton_PCaliSetPower.setText(_translate("SetupMainWindow", "Set Power"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_LaserCalibration), _translate("SetupMainWindow", "AOTF Power Calibration"))
        self.label_62.setText(_translate("SetupMainWindow", "M Delay (ms):"))
        self.pushButton_LIM_Measure.setText(_translate("SetupMainWindow", "Measure"))
        self.label_60.setText(_translate("SetupMainWindow", "X:"))
        self.label_63.setText(_translate("SetupMainWindow", "Y:"))
        self.label_41.setText(_translate("SetupMainWindow", "WL1:"))
        self.label_40.setText(_translate("SetupMainWindow", "WL:"))
        self.label_58.setText(_translate("SetupMainWindow", "Power%:"))
        self.pushButton_LIM_ShowResult.setText(_translate("SetupMainWindow", "Show Result"))
        self.label_39.setText(_translate("SetupMainWindow", "WL0:"))
        self.pushButton_LIM_LoadCaliPower.setText(_translate("SetupMainWindow", "Load Cali Res"))
        self.label_61.setText(_translate("SetupMainWindow", "WLs:"))
        self.pushButton_LIM_NextWL.setText(_translate("SetupMainWindow", "Next WL"))
        self.pushButton_LIM_Auto.setText(_translate("SetupMainWindow", "Auto Measure"))
        self.pushButton_LIM_SetWL0.setText(_translate("SetupMainWindow", "Set WL0"))
        self.label_59.setText(_translate("SetupMainWindow", "Cali Power%:"))
        self.pushButton_LIM_SetCaliPower.setText(_translate("SetupMainWindow", "Set Cali Power"))
        self.pushButton_LIM_SetPower.setText(_translate("SetupMainWindow", "Set Power"))
        self.label_56.setText(_translate("SetupMainWindow", "Power:"))
        self.pushButton_LIM_ClearPlots.setText(_translate("SetupMainWindow", "Clear Plots"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_LockInMeasurements), _translate("SetupMainWindow", "Lock-In Measurements"))
        self.label_46.setText(_translate("SetupMainWindow", "X1:"))
        self.label_45.setText(_translate("SetupMainWindow", "X0:"))
        self.pushButton_MapM_GoY0.setText(_translate("SetupMainWindow", "Go Y0"))
        self.pushButton_MapM_GoX0.setText(_translate("SetupMainWindow", "Go X0"))
        self.label_72.setText(_translate("SetupMainWindow", "LockIn X:"))
        self.label_44.setText(_translate("SetupMainWindow", "Y0:"))
        self.label_73.setText(_translate("SetupMainWindow", "LockIn Y:"))
        self.label_69.setText(_translate("SetupMainWindow", "#YSample:"))
        self.label_68.setText(_translate("SetupMainWindow", "#XSample:"))
        self.label_70.setText(_translate("SetupMainWindow", "X Step:"))
        self.label_71.setText(_translate("SetupMainWindow", "Y Step:"))
        self.label_47.setText(_translate("SetupMainWindow", "Y1:"))
        self.label_48.setText(_translate("SetupMainWindow", "Sine Input:"))
        self.label_64.setText(_translate("SetupMainWindow", "NIDAQ Ch:"))
        self.label_65.setText(_translate("SetupMainWindow", "M Delay (ms):"))
        self.pushButton_MapM_Measure.setText(_translate("SetupMainWindow", "Measure"))
        self.pushButton_MapM_Auto.setText(_translate("SetupMainWindow", "Auto Measure"))
        self.pushButton_MapM_Export.setText(_translate("SetupMainWindow", "Export"))
        self.pushButton_MapM_Load.setText(_translate("SetupMainWindow", "Load Raw"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_MapMeasurements), _translate("SetupMainWindow", "Map Measurements"))


from ..LaserProfiler.laser_profiler_widget import LaserProfilerWidget
from ..LaserProfiler.laser_profiler_zdepth_widget import LaserProfilerZDepthWidget
from .lockin_plot_widget import LockInPlotWidget
from ..MeasurementPlot.measurement_plot_widget import MeasurementPlotWidget
from .pcali_plot_widget import PCaliPlotWidget
from .pdv_plot_widget import PDVPlotWidget
