# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'aotf_config.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AOTF_Config_Window(object):
    def setupUi(self, AOTF_Config_Window):
        AOTF_Config_Window.setObjectName("AOTF_Config_Window")
        AOTF_Config_Window.resize(441, 378)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(AOTF_Config_Window)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_Conn = QtWidgets.QGroupBox(AOTF_Config_Window)
        self.groupBox_Conn.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_Conn.setObjectName("groupBox_Conn")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.groupBox_Conn)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setContentsMargins(6, -1, 6, -1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineEdit_LibPath = QtWidgets.QLineEdit(self.groupBox_Conn)
        self.lineEdit_LibPath.setObjectName("lineEdit_LibPath")
        self.gridLayout_3.addWidget(self.lineEdit_LibPath, 0, 1, 1, 1)
        self.label_Conn_Status = QtWidgets.QLabel(self.groupBox_Conn)
        self.label_Conn_Status.setMinimumSize(QtCore.QSize(0, 0))
        self.label_Conn_Status.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_Conn_Status.setStyleSheet("background : red")
        self.label_Conn_Status.setText("")
        self.label_Conn_Status.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Conn_Status.setObjectName("label_Conn_Status")
        self.gridLayout_3.addWidget(self.label_Conn_Status, 1, 0, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.groupBox_Conn)
        self.label_37.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_37.setObjectName("label_37")
        self.gridLayout_3.addWidget(self.label_37, 0, 0, 1, 1)
        self.pushButton_LibLoc = QtWidgets.QPushButton(self.groupBox_Conn)
        self.pushButton_LibLoc.setObjectName("pushButton_LibLoc")
        self.gridLayout_3.addWidget(self.pushButton_LibLoc, 0, 2, 1, 1)
        self.pushButton_Conn = QtWidgets.QPushButton(self.groupBox_Conn)
        self.pushButton_Conn.setCheckable(True)
        self.pushButton_Conn.setObjectName("pushButton_Conn")
        self.gridLayout_3.addWidget(self.pushButton_Conn, 1, 1, 1, 2)
        self.gridLayout_3.setColumnStretch(1, 1)
        self.verticalLayout_10.addLayout(self.gridLayout_3)
        self.verticalLayout_3.addWidget(self.groupBox_Conn)
        self.groupBox_Config = QtWidgets.QGroupBox(AOTF_Config_Window)
        self.groupBox_Config.setEnabled(False)
        self.groupBox_Config.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_Config.setObjectName("groupBox_Config")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_Config)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_12 = QtWidgets.QLabel(self.groupBox_Config)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 0, 0, 1, 1)
        self.radioButton_RF1 = QtWidgets.QRadioButton(self.groupBox_Config)
        self.radioButton_RF1.setChecked(True)
        self.radioButton_RF1.setObjectName("radioButton_RF1")
        self.gridLayout.addWidget(self.radioButton_RF1, 0, 1, 1, 1)
        self.radioButton_RF2 = QtWidgets.QRadioButton(self.groupBox_Config)
        self.radioButton_RF2.setObjectName("radioButton_RF2")
        self.gridLayout.addWidget(self.radioButton_RF2, 0, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_Config)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 1, 0, 1, 1)
        self.spinBox_WaveLength = QtWidgets.QSpinBox(self.groupBox_Config)
        self.spinBox_WaveLength.setKeyboardTracking(False)
        self.spinBox_WaveLength.setMinimum(400)
        self.spinBox_WaveLength.setMaximum(2200)
        self.spinBox_WaveLength.setSingleStep(100)
        self.spinBox_WaveLength.setProperty("value", 450)
        self.spinBox_WaveLength.setObjectName("spinBox_WaveLength")
        self.gridLayout.addWidget(self.spinBox_WaveLength, 1, 1, 1, 1)
        self.pushButton_SetWaveLength = QtWidgets.QPushButton(self.groupBox_Config)
        self.pushButton_SetWaveLength.setObjectName("pushButton_SetWaveLength")
        self.gridLayout.addWidget(self.pushButton_SetWaveLength, 1, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_Config)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 2, 0, 1, 1)
        self.pushButton_SetPower = QtWidgets.QPushButton(self.groupBox_Config)
        self.pushButton_SetPower.setObjectName("pushButton_SetPower")
        self.gridLayout.addWidget(self.pushButton_SetPower, 2, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_Config)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 3, 0, 1, 1)
        self.doubleSpinBox_PowerPerc = QtWidgets.QDoubleSpinBox(self.groupBox_Config)
        self.doubleSpinBox_PowerPerc.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_PowerPerc.setKeyboardTracking(True)
        self.doubleSpinBox_PowerPerc.setMaximum(100.0)
        self.doubleSpinBox_PowerPerc.setObjectName("doubleSpinBox_PowerPerc")
        self.gridLayout.addWidget(self.doubleSpinBox_PowerPerc, 3, 1, 1, 1)
        self.pushButton_SetPowerPerc = QtWidgets.QPushButton(self.groupBox_Config)
        self.pushButton_SetPowerPerc.setObjectName("pushButton_SetPowerPerc")
        self.gridLayout.addWidget(self.pushButton_SetPowerPerc, 3, 2, 1, 1)
        self.doubleSpinBox_Power = QtWidgets.QDoubleSpinBox(self.groupBox_Config)
        self.doubleSpinBox_Power.setDecimals(1)
        self.doubleSpinBox_Power.setMaximum(16383.0)
        self.doubleSpinBox_Power.setSingleStep(100.0)
        self.doubleSpinBox_Power.setObjectName("doubleSpinBox_Power")
        self.gridLayout.addWidget(self.doubleSpinBox_Power, 2, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.verticalLayout_3.addWidget(self.groupBox_Config)
        spacerItem = QtWidgets.QSpacerItem(20, 2, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)

        self.retranslateUi(AOTF_Config_Window)
        QtCore.QMetaObject.connectSlotsByName(AOTF_Config_Window)
        AOTF_Config_Window.setTabOrder(self.lineEdit_LibPath, self.pushButton_LibLoc)
        AOTF_Config_Window.setTabOrder(self.pushButton_LibLoc, self.pushButton_Conn)
        AOTF_Config_Window.setTabOrder(self.pushButton_Conn, self.spinBox_WaveLength)
        AOTF_Config_Window.setTabOrder(self.spinBox_WaveLength, self.pushButton_SetWaveLength)
        AOTF_Config_Window.setTabOrder(self.pushButton_SetWaveLength, self.pushButton_SetPower)
        AOTF_Config_Window.setTabOrder(self.pushButton_SetPower, self.doubleSpinBox_PowerPerc)
        AOTF_Config_Window.setTabOrder(self.doubleSpinBox_PowerPerc, self.pushButton_SetPowerPerc)

    def retranslateUi(self, AOTF_Config_Window):
        _translate = QtCore.QCoreApplication.translate
        AOTF_Config_Window.setWindowTitle(_translate("AOTF_Config_Window", "AOTF Configuration"))
        self.groupBox_Conn.setTitle(_translate("AOTF_Config_Window", "AOTF Connection"))
        self.label_37.setText(_translate("AOTF_Config_Window", "AotfLib:"))
        self.pushButton_LibLoc.setText(_translate("AOTF_Config_Window", "..."))
        self.pushButton_Conn.setToolTip(_translate("AOTF_Config_Window", "Load the DLL library (Windows Only)"))
        self.pushButton_Conn.setText(_translate("AOTF_Config_Window", "Open"))
        self.groupBox_Config.setTitle(_translate("AOTF_Config_Window", "AOTF Configuration"))
        self.label_12.setText(_translate("AOTF_Config_Window", "Mode:"))
        self.radioButton_RF1.setText(_translate("AOTF_Config_Window", "RF1"))
        self.radioButton_RF2.setText(_translate("AOTF_Config_Window", "RF2"))
        self.label_11.setText(_translate("AOTF_Config_Window", "WLen (nm):"))
        self.pushButton_SetWaveLength.setText(_translate("AOTF_Config_Window", "Set"))
        self.label_13.setText(_translate("AOTF_Config_Window", "Power:"))
        self.pushButton_SetPower.setText(_translate("AOTF_Config_Window", "Set"))
        self.label_14.setText(_translate("AOTF_Config_Window", "Power(%):"))
        self.pushButton_SetPowerPerc.setText(_translate("AOTF_Config_Window", "Set"))


