# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'aotf_config.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AOTF_Config_Window(object):
    def setupUi(self, AOTF_Config_Window):
        AOTF_Config_Window.setObjectName("AOTF_Config_Window")
        AOTF_Config_Window.resize(434, 436)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(AOTF_Config_Window)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_Conn = QtWidgets.QGroupBox(AOTF_Config_Window)
        self.groupBox_Conn.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_Conn.setObjectName("groupBox_Conn")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.groupBox_Conn)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setContentsMargins(6, -1, 6, -1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineEdit_LibPath = QtWidgets.QLineEdit(self.groupBox_Conn)
        self.lineEdit_LibPath.setObjectName("lineEdit_LibPath")
        self.gridLayout_3.addWidget(self.lineEdit_LibPath, 0, 1, 1, 1)
        self.label_Conn_Status = QtWidgets.QLabel(self.groupBox_Conn)
        self.label_Conn_Status.setMinimumSize(QtCore.QSize(0, 0))
        self.label_Conn_Status.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_Conn_Status.setStyleSheet("background : red")
        self.label_Conn_Status.setText("")
        self.label_Conn_Status.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Conn_Status.setObjectName("label_Conn_Status")
        self.gridLayout_3.addWidget(self.label_Conn_Status, 1, 0, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.groupBox_Conn)
        self.label_37.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_37.setObjectName("label_37")
        self.gridLayout_3.addWidget(self.label_37, 0, 0, 1, 1)
        self.pushButton_LibLoc = QtWidgets.QPushButton(self.groupBox_Conn)
        self.pushButton_LibLoc.setObjectName("pushButton_LibLoc")
        self.gridLayout_3.addWidget(self.pushButton_LibLoc, 0, 2, 1, 1)
        self.pushButton_Conn = QtWidgets.QPushButton(self.groupBox_Conn)
        self.pushButton_Conn.setCheckable(True)
        self.pushButton_Conn.setObjectName("pushButton_Conn")
        self.gridLayout_3.addWidget(self.pushButton_Conn, 1, 1, 1, 2)
        self.gridLayout_3.setColumnStretch(1, 1)
        self.verticalLayout_10.addLayout(self.gridLayout_3)
        self.verticalLayout_3.addWidget(self.groupBox_Conn)
        self.groupBox_Config = QtWidgets.QGroupBox(AOTF_Config_Window)
        self.groupBox_Config.setEnabled(False)
        self.groupBox_Config.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_Config.setObjectName("groupBox_Config")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_Config)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_Device = QtWidgets.QGroupBox(self.groupBox_Config)
        self.groupBox_Device.setObjectName("groupBox_Device")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_Device)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox_Device)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit_AOTF1Serial = QtWidgets.QLineEdit(self.groupBox_Device)
        self.lineEdit_AOTF1Serial.setReadOnly(True)
        self.lineEdit_AOTF1Serial.setObjectName("lineEdit_AOTF1Serial")
        self.gridLayout_2.addWidget(self.lineEdit_AOTF1Serial, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_Device)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 3, 1, 1)
        self.comboBox_AOTF1Mode = QtWidgets.QComboBox(self.groupBox_Device)
        self.comboBox_AOTF1Mode.setObjectName("comboBox_AOTF1Mode")
        self.comboBox_AOTF1Mode.addItem("")
        self.comboBox_AOTF1Mode.addItem("")
        self.comboBox_AOTF1Mode.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_AOTF1Mode, 0, 4, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_Device)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.lineEdit_AOTF2Serial = QtWidgets.QLineEdit(self.groupBox_Device)
        self.lineEdit_AOTF2Serial.setReadOnly(True)
        self.lineEdit_AOTF2Serial.setObjectName("lineEdit_AOTF2Serial")
        self.gridLayout_2.addWidget(self.lineEdit_AOTF2Serial, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_Device)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 3, 1, 1)
        self.comboBox_AOTF2Mode = QtWidgets.QComboBox(self.groupBox_Device)
        self.comboBox_AOTF2Mode.setObjectName("comboBox_AOTF2Mode")
        self.comboBox_AOTF2Mode.addItem("")
        self.comboBox_AOTF2Mode.addItem("")
        self.comboBox_AOTF2Mode.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_AOTF2Mode, 1, 4, 1, 1)
        self.label_AOTF1_Status = QtWidgets.QLabel(self.groupBox_Device)
        self.label_AOTF1_Status.setMinimumSize(QtCore.QSize(40, 0))
        self.label_AOTF1_Status.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_AOTF1_Status.setStyleSheet("background : red")
        self.label_AOTF1_Status.setText("")
        self.label_AOTF1_Status.setAlignment(QtCore.Qt.AlignCenter)
        self.label_AOTF1_Status.setObjectName("label_AOTF1_Status")
        self.gridLayout_2.addWidget(self.label_AOTF1_Status, 0, 2, 1, 1)
        self.label_AOTF2_Status = QtWidgets.QLabel(self.groupBox_Device)
        self.label_AOTF2_Status.setMinimumSize(QtCore.QSize(0, 0))
        self.label_AOTF2_Status.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_AOTF2_Status.setStyleSheet("background : red")
        self.label_AOTF2_Status.setText("")
        self.label_AOTF2_Status.setAlignment(QtCore.Qt.AlignCenter)
        self.label_AOTF2_Status.setObjectName("label_AOTF2_Status")
        self.gridLayout_2.addWidget(self.label_AOTF2_Status, 1, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.verticalLayout_2.addWidget(self.groupBox_Device)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_SetOptimalPower = QtWidgets.QPushButton(self.groupBox_Config)
        self.pushButton_SetOptimalPower.setObjectName("pushButton_SetOptimalPower")
        self.gridLayout.addWidget(self.pushButton_SetOptimalPower, 1, 3, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_Config)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 0, 0, 1, 2)
        self.pushButton_SetPowerPerc = QtWidgets.QPushButton(self.groupBox_Config)
        self.pushButton_SetPowerPerc.setObjectName("pushButton_SetPowerPerc")
        self.gridLayout.addWidget(self.pushButton_SetPowerPerc, 3, 3, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_Config)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 1, 0, 1, 2)
        self.lineEdit_Power = QtWidgets.QLineEdit(self.groupBox_Config)
        self.lineEdit_Power.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_Power.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.lineEdit_Power.setObjectName("lineEdit_Power")
        self.gridLayout.addWidget(self.lineEdit_Power, 2, 2, 1, 1)
        self.lineEdit_OptimalPower = QtWidgets.QLineEdit(self.groupBox_Config)
        self.lineEdit_OptimalPower.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_OptimalPower.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.lineEdit_OptimalPower.setReadOnly(True)
        self.lineEdit_OptimalPower.setObjectName("lineEdit_OptimalPower")
        self.gridLayout.addWidget(self.lineEdit_OptimalPower, 1, 2, 1, 1)
        self.pushButton_SetPower = QtWidgets.QPushButton(self.groupBox_Config)
        self.pushButton_SetPower.setObjectName("pushButton_SetPower")
        self.gridLayout.addWidget(self.pushButton_SetPower, 2, 3, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_Config)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 3, 0, 1, 2)
        self.doubleSpinBox_PowerPerc = QtWidgets.QDoubleSpinBox(self.groupBox_Config)
        self.doubleSpinBox_PowerPerc.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_PowerPerc.setKeyboardTracking(True)
        self.doubleSpinBox_PowerPerc.setMaximum(100.0)
        self.doubleSpinBox_PowerPerc.setObjectName("doubleSpinBox_PowerPerc")
        self.gridLayout.addWidget(self.doubleSpinBox_PowerPerc, 3, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_Config)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 2, 0, 1, 2)
        self.spinBox_WaveLength = QtWidgets.QSpinBox(self.groupBox_Config)
        self.spinBox_WaveLength.setKeyboardTracking(False)
        self.spinBox_WaveLength.setMinimum(400)
        self.spinBox_WaveLength.setMaximum(2200)
        self.spinBox_WaveLength.setSingleStep(100)
        self.spinBox_WaveLength.setProperty("value", 450)
        self.spinBox_WaveLength.setObjectName("spinBox_WaveLength")
        self.gridLayout.addWidget(self.spinBox_WaveLength, 0, 2, 1, 1)
        self.pushButton_SetWaveLength = QtWidgets.QPushButton(self.groupBox_Config)
        self.pushButton_SetWaveLength.setObjectName("pushButton_SetWaveLength")
        self.gridLayout.addWidget(self.pushButton_SetWaveLength, 0, 3, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.verticalLayout_3.addWidget(self.groupBox_Config)
        spacerItem = QtWidgets.QSpacerItem(20, 2, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)

        self.retranslateUi(AOTF_Config_Window)
        self.comboBox_AOTF2Mode.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(AOTF_Config_Window)

    def retranslateUi(self, AOTF_Config_Window):
        _translate = QtCore.QCoreApplication.translate
        AOTF_Config_Window.setWindowTitle(_translate("AOTF_Config_Window", "AOTF Configuration"))
        self.groupBox_Conn.setTitle(_translate("AOTF_Config_Window", "AOTF Connection"))
        self.label_37.setText(_translate("AOTF_Config_Window", "AotfLib:"))
        self.pushButton_LibLoc.setText(_translate("AOTF_Config_Window", "..."))
        self.pushButton_Conn.setToolTip(_translate("AOTF_Config_Window", "Load the DLL library (Windows Only)"))
        self.pushButton_Conn.setText(_translate("AOTF_Config_Window", "Open"))
        self.groupBox_Config.setTitle(_translate("AOTF_Config_Window", "AOTF Configuration"))
        self.groupBox_Device.setTitle(_translate("AOTF_Config_Window", "AOTF Devices"))
        self.label.setText(_translate("AOTF_Config_Window", "AOTF1:"))
        self.label_2.setText(_translate("AOTF_Config_Window", "Mode:"))
        self.comboBox_AOTF1Mode.setItemText(0, _translate("AOTF_Config_Window", "VIS"))
        self.comboBox_AOTF1Mode.setItemText(1, _translate("AOTF_Config_Window", "NIR1"))
        self.comboBox_AOTF1Mode.setItemText(2, _translate("AOTF_Config_Window", "NIR2"))
        self.label_3.setText(_translate("AOTF_Config_Window", "AOTF2:"))
        self.label_4.setText(_translate("AOTF_Config_Window", "Mode:"))
        self.comboBox_AOTF2Mode.setItemText(0, _translate("AOTF_Config_Window", "VIS"))
        self.comboBox_AOTF2Mode.setItemText(1, _translate("AOTF_Config_Window", "NIR1"))
        self.comboBox_AOTF2Mode.setItemText(2, _translate("AOTF_Config_Window", "NIR2"))
        self.pushButton_SetOptimalPower.setText(_translate("AOTF_Config_Window", "Set"))
        self.label_11.setText(_translate("AOTF_Config_Window", "Wave Length (nm):"))
        self.pushButton_SetPowerPerc.setText(_translate("AOTF_Config_Window", "Set"))
        self.label_10.setText(_translate("AOTF_Config_Window", "Optimimal Power:"))
        self.lineEdit_Power.setToolTip(_translate("AOTF_Config_Window", "SR830 Phase (float)"))
        self.lineEdit_Power.setText(_translate("AOTF_Config_Window", "0"))
        self.lineEdit_OptimalPower.setToolTip(_translate("AOTF_Config_Window", "SR830 Phase (float)"))
        self.pushButton_SetPower.setText(_translate("AOTF_Config_Window", "Set"))
        self.label_14.setText(_translate("AOTF_Config_Window", "Power(%):"))
        self.label_13.setText(_translate("AOTF_Config_Window", "Power:"))
        self.pushButton_SetWaveLength.setText(_translate("AOTF_Config_Window", "Set"))
