# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'piezo_config.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Piezo_Config_Window(object):
    def setupUi(self, Piezo_Config_Window):
        Piezo_Config_Window.setObjectName("Piezo_Config_Window")
        Piezo_Config_Window.resize(715, 907)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(Piezo_Config_Window)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox_COM = QtWidgets.QGroupBox(Piezo_Config_Window)
        self.groupBox_COM.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_COM.setObjectName("groupBox_COM")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.groupBox_COM)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setContentsMargins(6, -1, 6, -1)
        self.gridLayout_7.setHorizontalSpacing(10)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_22 = QtWidgets.QLabel(self.groupBox_COM)
        self.label_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName("label_22")
        self.gridLayout_7.addWidget(self.label_22, 1, 0, 1, 1)
        self.comboBox_COM = QtWidgets.QComboBox(self.groupBox_COM)
        self.comboBox_COM.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_COM.sizePolicy().hasHeightForWidth())
        self.comboBox_COM.setSizePolicy(sizePolicy)
        self.comboBox_COM.setObjectName("comboBox_COM")
        self.gridLayout_7.addWidget(self.comboBox_COM, 0, 1, 1, 2)
        self.comboBox_COM_Parity = QtWidgets.QComboBox(self.groupBox_COM)
        self.comboBox_COM_Parity.setObjectName("comboBox_COM_Parity")
        self.comboBox_COM_Parity.addItem("")
        self.comboBox_COM_Parity.addItem("")
        self.comboBox_COM_Parity.addItem("")
        self.gridLayout_7.addWidget(self.comboBox_COM_Parity, 2, 1, 1, 2)
        self.label_COM_Status = QtWidgets.QLabel(self.groupBox_COM)
        self.label_COM_Status.setStyleSheet("background : red")
        self.label_COM_Status.setText("")
        self.label_COM_Status.setAlignment(QtCore.Qt.AlignCenter)
        self.label_COM_Status.setObjectName("label_COM_Status")
        self.gridLayout_7.addWidget(self.label_COM_Status, 4, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.groupBox_COM)
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.gridLayout_7.addWidget(self.label_21, 0, 0, 1, 1)
        self.comboBox_COM_Baudrate = QtWidgets.QComboBox(self.groupBox_COM)
        self.comboBox_COM_Baudrate.setObjectName("comboBox_COM_Baudrate")
        self.comboBox_COM_Baudrate.addItem("")
        self.comboBox_COM_Baudrate.addItem("")
        self.comboBox_COM_Baudrate.addItem("")
        self.comboBox_COM_Baudrate.addItem("")
        self.comboBox_COM_Baudrate.addItem("")
        self.gridLayout_7.addWidget(self.comboBox_COM_Baudrate, 1, 1, 1, 2)
        self.pushButton_COM_Open = QtWidgets.QPushButton(self.groupBox_COM)
        self.pushButton_COM_Open.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_COM_Open.setCheckable(True)
        self.pushButton_COM_Open.setFlat(False)
        self.pushButton_COM_Open.setObjectName("pushButton_COM_Open")
        self.gridLayout_7.addWidget(self.pushButton_COM_Open, 4, 2, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.groupBox_COM)
        self.label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.gridLayout_7.addWidget(self.label_23, 2, 0, 1, 1)
        self.pushButton_COM_Refresh = QtWidgets.QPushButton(self.groupBox_COM)
        self.pushButton_COM_Refresh.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_COM_Refresh.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_COM_Refresh.setCheckable(False)
        self.pushButton_COM_Refresh.setObjectName("pushButton_COM_Refresh")
        self.gridLayout_7.addWidget(self.pushButton_COM_Refresh, 4, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.groupBox_COM)
        self.label_24.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName("label_24")
        self.gridLayout_7.addWidget(self.label_24, 3, 0, 1, 1)
        self.comboBox_COM_Stopbits = QtWidgets.QComboBox(self.groupBox_COM)
        self.comboBox_COM_Stopbits.setObjectName("comboBox_COM_Stopbits")
        self.comboBox_COM_Stopbits.addItem("")
        self.comboBox_COM_Stopbits.addItem("")
        self.comboBox_COM_Stopbits.addItem("")
        self.gridLayout_7.addWidget(self.comboBox_COM_Stopbits, 3, 1, 1, 2)
        self.verticalLayout_12.addLayout(self.gridLayout_7)
        self.verticalLayout_6.addWidget(self.groupBox_COM)
        self.groupBox_Control = QtWidgets.QGroupBox(Piezo_Config_Window)
        self.groupBox_Control.setEnabled(False)
        self.groupBox_Control.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_Control.setObjectName("groupBox_Control")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_Control)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(20)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.groupBox_Control)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.radioButton_Online = QtWidgets.QRadioButton(self.groupBox_Control)
        self.radioButton_Online.setObjectName("radioButton_Online")
        self.horizontalLayout_4.addWidget(self.radioButton_Online)
        self.radioButton_Offline = QtWidgets.QRadioButton(self.groupBox_Control)
        self.radioButton_Offline.setChecked(True)
        self.radioButton_Offline.setObjectName("radioButton_Offline")
        self.horizontalLayout_4.addWidget(self.radioButton_Offline)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.groupBox_Control_Online = QtWidgets.QGroupBox(self.groupBox_Control)
        self.groupBox_Control_Online.setEnabled(False)
        self.groupBox_Control_Online.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_Control_Online.setObjectName("groupBox_Control_Online")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_Control_Online)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox_Control_Online)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.radioButton_ClosedLoop = QtWidgets.QRadioButton(self.groupBox_Control_Online)
        self.radioButton_ClosedLoop.setChecked(True)
        self.radioButton_ClosedLoop.setObjectName("radioButton_ClosedLoop")
        self.horizontalLayout.addWidget(self.radioButton_ClosedLoop)
        self.radioButton_OpenLoop = QtWidgets.QRadioButton(self.groupBox_Control_Online)
        self.radioButton_OpenLoop.setObjectName("radioButton_OpenLoop")
        self.horizontalLayout.addWidget(self.radioButton_OpenLoop)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pushButton_Sync = QtWidgets.QPushButton(self.groupBox_Control_Online)
        self.pushButton_Sync.setObjectName("pushButton_Sync")
        self.horizontalLayout.addWidget(self.pushButton_Sync)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.groupBox_VelControl = QtWidgets.QGroupBox(self.groupBox_Control_Online)
        self.groupBox_VelControl.setObjectName("groupBox_VelControl")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_VelControl)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_56 = QtWidgets.QLabel(self.groupBox_VelControl)
        self.label_56.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_56.setObjectName("label_56")
        self.gridLayout.addWidget(self.label_56, 0, 0, 1, 1)
        self.checkBox_VelCtrlX = QtWidgets.QCheckBox(self.groupBox_VelControl)
        self.checkBox_VelCtrlX.setObjectName("checkBox_VelCtrlX")
        self.gridLayout.addWidget(self.checkBox_VelCtrlX, 0, 1, 1, 1)
        self.doubleSpinBox_XVel = QtWidgets.QDoubleSpinBox(self.groupBox_VelControl)
        self.doubleSpinBox_XVel.setKeyboardTracking(False)
        self.doubleSpinBox_XVel.setDecimals(6)
        self.doubleSpinBox_XVel.setMaximum(100.0)
        self.doubleSpinBox_XVel.setSingleStep(0.01)
        self.doubleSpinBox_XVel.setObjectName("doubleSpinBox_XVel")
        self.gridLayout.addWidget(self.doubleSpinBox_XVel, 0, 2, 1, 1)
        self.label_VelUnit = QtWidgets.QLabel(self.groupBox_VelControl)
        self.label_VelUnit.setAlignment(QtCore.Qt.AlignCenter)
        self.label_VelUnit.setObjectName("label_VelUnit")
        self.gridLayout.addWidget(self.label_VelUnit, 0, 3, 3, 1)
        self.label_55 = QtWidgets.QLabel(self.groupBox_VelControl)
        self.label_55.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_55.setObjectName("label_55")
        self.gridLayout.addWidget(self.label_55, 1, 0, 1, 1)
        self.checkBox_VelCtrlY = QtWidgets.QCheckBox(self.groupBox_VelControl)
        self.checkBox_VelCtrlY.setObjectName("checkBox_VelCtrlY")
        self.gridLayout.addWidget(self.checkBox_VelCtrlY, 1, 1, 1, 1)
        self.doubleSpinBox_YVel = QtWidgets.QDoubleSpinBox(self.groupBox_VelControl)
        self.doubleSpinBox_YVel.setKeyboardTracking(False)
        self.doubleSpinBox_YVel.setDecimals(6)
        self.doubleSpinBox_YVel.setMaximum(100.0)
        self.doubleSpinBox_YVel.setSingleStep(0.01)
        self.doubleSpinBox_YVel.setObjectName("doubleSpinBox_YVel")
        self.gridLayout.addWidget(self.doubleSpinBox_YVel, 1, 2, 1, 1)
        self.label_54 = QtWidgets.QLabel(self.groupBox_VelControl)
        self.label_54.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_54.setObjectName("label_54")
        self.gridLayout.addWidget(self.label_54, 2, 0, 1, 1)
        self.checkBox_VelCtrlZ = QtWidgets.QCheckBox(self.groupBox_VelControl)
        self.checkBox_VelCtrlZ.setObjectName("checkBox_VelCtrlZ")
        self.gridLayout.addWidget(self.checkBox_VelCtrlZ, 2, 1, 1, 1)
        self.doubleSpinBox_ZVel = QtWidgets.QDoubleSpinBox(self.groupBox_VelControl)
        self.doubleSpinBox_ZVel.setKeyboardTracking(False)
        self.doubleSpinBox_ZVel.setDecimals(6)
        self.doubleSpinBox_ZVel.setMaximum(100.0)
        self.doubleSpinBox_ZVel.setSingleStep(0.01)
        self.doubleSpinBox_ZVel.setObjectName("doubleSpinBox_ZVel")
        self.gridLayout.addWidget(self.doubleSpinBox_ZVel, 2, 2, 1, 1)
        self.pushButton_GetVel = QtWidgets.QPushButton(self.groupBox_VelControl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_GetVel.sizePolicy().hasHeightForWidth())
        self.pushButton_GetVel.setSizePolicy(sizePolicy)
        self.pushButton_GetVel.setObjectName("pushButton_GetVel")
        self.gridLayout.addWidget(self.pushButton_GetVel, 0, 4, 3, 1)
        self.pushButton_SetVel = QtWidgets.QPushButton(self.groupBox_VelControl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_SetVel.sizePolicy().hasHeightForWidth())
        self.pushButton_SetVel.setSizePolicy(sizePolicy)
        self.pushButton_SetVel.setObjectName("pushButton_SetVel")
        self.gridLayout.addWidget(self.pushButton_SetVel, 0, 5, 3, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.verticalLayout_3.addWidget(self.groupBox_VelControl)
        self.groupBox_Control_ClosedLoop = QtWidgets.QGroupBox(self.groupBox_Control_Online)
        self.groupBox_Control_ClosedLoop.setEnabled(False)
        self.groupBox_Control_ClosedLoop.setObjectName("groupBox_Control_ClosedLoop")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_Control_ClosedLoop)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout_ClosedLoop = QtWidgets.QGridLayout()
        self.gridLayout_ClosedLoop.setContentsMargins(6, -1, 6, -1)
        self.gridLayout_ClosedLoop.setObjectName("gridLayout_ClosedLoop")
        self.label_YMAX_C = QtWidgets.QLabel(self.groupBox_Control_ClosedLoop)
        self.label_YMAX_C.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_YMAX_C.setObjectName("label_YMAX_C")
        self.gridLayout_ClosedLoop.addWidget(self.label_YMAX_C, 1, 2, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.groupBox_Control_ClosedLoop)
        self.label_47.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_47.setObjectName("label_47")
        self.gridLayout_ClosedLoop.addWidget(self.label_47, 1, 3, 1, 1)
        self.label_ZMAX_C = QtWidgets.QLabel(self.groupBox_Control_ClosedLoop)
        self.label_ZMAX_C.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_ZMAX_C.setObjectName("label_ZMAX_C")
        self.gridLayout_ClosedLoop.addWidget(self.label_ZMAX_C, 2, 2, 1, 1)
        self.label_50 = QtWidgets.QLabel(self.groupBox_Control_ClosedLoop)
        self.label_50.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_50.setObjectName("label_50")
        self.gridLayout_ClosedLoop.addWidget(self.label_50, 0, 3, 1, 1)
        self.label_XMAX_C = QtWidgets.QLabel(self.groupBox_Control_ClosedLoop)
        self.label_XMAX_C.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_XMAX_C.setObjectName("label_XMAX_C")
        self.gridLayout_ClosedLoop.addWidget(self.label_XMAX_C, 0, 2, 1, 1)
        self.label_52 = QtWidgets.QLabel(self.groupBox_Control_ClosedLoop)
        self.label_52.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_52.setObjectName("label_52")
        self.gridLayout_ClosedLoop.addWidget(self.label_52, 2, 5, 1, 1)
        self.label_XCurrentPos_C = QtWidgets.QLabel(self.groupBox_Control_ClosedLoop)
        self.label_XCurrentPos_C.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_XCurrentPos_C.setObjectName("label_XCurrentPos_C")
        self.gridLayout_ClosedLoop.addWidget(self.label_XCurrentPos_C, 0, 6, 1, 1)
        self.label_53 = QtWidgets.QLabel(self.groupBox_Control_ClosedLoop)
        self.label_53.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_53.setObjectName("label_53")
        self.gridLayout_ClosedLoop.addWidget(self.label_53, 1, 5, 1, 1)
        self.doubleSpinBox_ZTarget_C = QtWidgets.QDoubleSpinBox(self.groupBox_Control_ClosedLoop)
        self.doubleSpinBox_ZTarget_C.setKeyboardTracking(False)
        self.doubleSpinBox_ZTarget_C.setMaximum(100.0)
        self.doubleSpinBox_ZTarget_C.setSingleStep(0.01)
        self.doubleSpinBox_ZTarget_C.setObjectName("doubleSpinBox_ZTarget_C")
        self.gridLayout_ClosedLoop.addWidget(self.doubleSpinBox_ZTarget_C, 2, 4, 1, 1)
        self.doubleSpinBox_XTarget_C = QtWidgets.QDoubleSpinBox(self.groupBox_Control_ClosedLoop)
        self.doubleSpinBox_XTarget_C.setKeyboardTracking(False)
        self.doubleSpinBox_XTarget_C.setMaximum(100.0)
        self.doubleSpinBox_XTarget_C.setSingleStep(0.01)
        self.doubleSpinBox_XTarget_C.setObjectName("doubleSpinBox_XTarget_C")
        self.gridLayout_ClosedLoop.addWidget(self.doubleSpinBox_XTarget_C, 0, 4, 1, 1)
        self.label_ZMIN_C = QtWidgets.QLabel(self.groupBox_Control_ClosedLoop)
        self.label_ZMIN_C.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_ZMIN_C.setObjectName("label_ZMIN_C")
        self.gridLayout_ClosedLoop.addWidget(self.label_ZMIN_C, 2, 1, 1, 1)
        self.label_49 = QtWidgets.QLabel(self.groupBox_Control_ClosedLoop)
        self.label_49.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_49.setObjectName("label_49")
        self.gridLayout_ClosedLoop.addWidget(self.label_49, 0, 5, 1, 1)
        self.label_YMIN_C = QtWidgets.QLabel(self.groupBox_Control_ClosedLoop)
        self.label_YMIN_C.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_YMIN_C.setObjectName("label_YMIN_C")
        self.gridLayout_ClosedLoop.addWidget(self.label_YMIN_C, 1, 1, 1, 1)
        self.label_XMIN_C = QtWidgets.QLabel(self.groupBox_Control_ClosedLoop)
        self.label_XMIN_C.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_XMIN_C.setObjectName("label_XMIN_C")
        self.gridLayout_ClosedLoop.addWidget(self.label_XMIN_C, 0, 1, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.groupBox_Control_ClosedLoop)
        self.label_45.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_45.setObjectName("label_45")
        self.gridLayout_ClosedLoop.addWidget(self.label_45, 2, 3, 1, 1)
        self.label_ZCurrentPos_C = QtWidgets.QLabel(self.groupBox_Control_ClosedLoop)
        self.label_ZCurrentPos_C.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_ZCurrentPos_C.setObjectName("label_ZCurrentPos_C")
        self.gridLayout_ClosedLoop.addWidget(self.label_ZCurrentPos_C, 2, 6, 1, 1)
        self.label_YCurrentPos_C = QtWidgets.QLabel(self.groupBox_Control_ClosedLoop)
        self.label_YCurrentPos_C.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_YCurrentPos_C.setObjectName("label_YCurrentPos_C")
        self.gridLayout_ClosedLoop.addWidget(self.label_YCurrentPos_C, 1, 6, 1, 1)
        self.doubleSpinBox_YTarget_C = QtWidgets.QDoubleSpinBox(self.groupBox_Control_ClosedLoop)
        self.doubleSpinBox_YTarget_C.setKeyboardTracking(False)
        self.doubleSpinBox_YTarget_C.setMaximum(100.0)
        self.doubleSpinBox_YTarget_C.setSingleStep(0.01)
        self.doubleSpinBox_YTarget_C.setObjectName("doubleSpinBox_YTarget_C")
        self.gridLayout_ClosedLoop.addWidget(self.doubleSpinBox_YTarget_C, 1, 4, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.groupBox_Control_ClosedLoop)
        self.label_46.setAlignment(QtCore.Qt.AlignCenter)
        self.label_46.setObjectName("label_46")
        self.gridLayout_ClosedLoop.addWidget(self.label_46, 0, 0, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.groupBox_Control_ClosedLoop)
        self.label_48.setAlignment(QtCore.Qt.AlignCenter)
        self.label_48.setObjectName("label_48")
        self.gridLayout_ClosedLoop.addWidget(self.label_48, 1, 0, 1, 1)
        self.label_51 = QtWidgets.QLabel(self.groupBox_Control_ClosedLoop)
        self.label_51.setAlignment(QtCore.Qt.AlignCenter)
        self.label_51.setObjectName("label_51")
        self.gridLayout_ClosedLoop.addWidget(self.label_51, 2, 0, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_ClosedLoop)
        self.verticalLayout_3.addWidget(self.groupBox_Control_ClosedLoop)
        self.line = QtWidgets.QFrame(self.groupBox_Control_Online)
        self.line.setLineWidth(4)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.groupBox_Control_OpenLoop = QtWidgets.QGroupBox(self.groupBox_Control_Online)
        self.groupBox_Control_OpenLoop.setEnabled(False)
        self.groupBox_Control_OpenLoop.setObjectName("groupBox_Control_OpenLoop")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_Control_OpenLoop)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout_OpenLoop = QtWidgets.QGridLayout()
        self.gridLayout_OpenLoop.setContentsMargins(6, -1, 6, -1)
        self.gridLayout_OpenLoop.setObjectName("gridLayout_OpenLoop")
        self.label_YMIN_O = QtWidgets.QLabel(self.groupBox_Control_OpenLoop)
        self.label_YMIN_O.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_YMIN_O.setObjectName("label_YMIN_O")
        self.gridLayout_OpenLoop.addWidget(self.label_YMIN_O, 1, 1, 1, 1)
        self.label_XMAX_O = QtWidgets.QLabel(self.groupBox_Control_OpenLoop)
        self.label_XMAX_O.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_XMAX_O.setObjectName("label_XMAX_O")
        self.gridLayout_OpenLoop.addWidget(self.label_XMAX_O, 0, 2, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.groupBox_Control_OpenLoop)
        self.label_29.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_29.setObjectName("label_29")
        self.gridLayout_OpenLoop.addWidget(self.label_29, 2, 3, 1, 1)
        self.label_ZCurrentPos_O = QtWidgets.QLabel(self.groupBox_Control_OpenLoop)
        self.label_ZCurrentPos_O.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_ZCurrentPos_O.setObjectName("label_ZCurrentPos_O")
        self.gridLayout_OpenLoop.addWidget(self.label_ZCurrentPos_O, 2, 6, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.groupBox_Control_OpenLoop)
        self.label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.label_33.setObjectName("label_33")
        self.gridLayout_OpenLoop.addWidget(self.label_33, 0, 0, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.groupBox_Control_OpenLoop)
        self.label_35.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_35.setObjectName("label_35")
        self.gridLayout_OpenLoop.addWidget(self.label_35, 1, 3, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.groupBox_Control_OpenLoop)
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.gridLayout_OpenLoop.addWidget(self.label_28, 1, 0, 1, 1)
        self.label_ZMAX_O = QtWidgets.QLabel(self.groupBox_Control_OpenLoop)
        self.label_ZMAX_O.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_ZMAX_O.setObjectName("label_ZMAX_O")
        self.gridLayout_OpenLoop.addWidget(self.label_ZMAX_O, 2, 2, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.groupBox_Control_OpenLoop)
        self.label_30.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_30.setObjectName("label_30")
        self.gridLayout_OpenLoop.addWidget(self.label_30, 0, 5, 1, 1)
        self.label_XMIN_O = QtWidgets.QLabel(self.groupBox_Control_OpenLoop)
        self.label_XMIN_O.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_XMIN_O.setObjectName("label_XMIN_O")
        self.gridLayout_OpenLoop.addWidget(self.label_XMIN_O, 0, 1, 1, 1)
        self.doubleSpinBox_XTarget_O = QtWidgets.QDoubleSpinBox(self.groupBox_Control_OpenLoop)
        self.doubleSpinBox_XTarget_O.setKeyboardTracking(False)
        self.doubleSpinBox_XTarget_O.setMaximum(100.0)
        self.doubleSpinBox_XTarget_O.setSingleStep(0.01)
        self.doubleSpinBox_XTarget_O.setObjectName("doubleSpinBox_XTarget_O")
        self.gridLayout_OpenLoop.addWidget(self.doubleSpinBox_XTarget_O, 0, 4, 1, 1)
        self.label_XCurrentPos_O = QtWidgets.QLabel(self.groupBox_Control_OpenLoop)
        self.label_XCurrentPos_O.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_XCurrentPos_O.setObjectName("label_XCurrentPos_O")
        self.gridLayout_OpenLoop.addWidget(self.label_XCurrentPos_O, 0, 6, 1, 1)
        self.label_YCurrentPos_O = QtWidgets.QLabel(self.groupBox_Control_OpenLoop)
        self.label_YCurrentPos_O.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_YCurrentPos_O.setObjectName("label_YCurrentPos_O")
        self.gridLayout_OpenLoop.addWidget(self.label_YCurrentPos_O, 1, 6, 1, 1)
        self.doubleSpinBox_YTarget_O = QtWidgets.QDoubleSpinBox(self.groupBox_Control_OpenLoop)
        self.doubleSpinBox_YTarget_O.setKeyboardTracking(False)
        self.doubleSpinBox_YTarget_O.setMaximum(100.0)
        self.doubleSpinBox_YTarget_O.setSingleStep(0.01)
        self.doubleSpinBox_YTarget_O.setObjectName("doubleSpinBox_YTarget_O")
        self.gridLayout_OpenLoop.addWidget(self.doubleSpinBox_YTarget_O, 1, 4, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.groupBox_Control_OpenLoop)
        self.label_27.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName("label_27")
        self.gridLayout_OpenLoop.addWidget(self.label_27, 0, 3, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.groupBox_Control_OpenLoop)
        self.label_34.setAlignment(QtCore.Qt.AlignCenter)
        self.label_34.setObjectName("label_34")
        self.gridLayout_OpenLoop.addWidget(self.label_34, 2, 0, 1, 1)
        self.label_YMAX_O = QtWidgets.QLabel(self.groupBox_Control_OpenLoop)
        self.label_YMAX_O.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_YMAX_O.setObjectName("label_YMAX_O")
        self.gridLayout_OpenLoop.addWidget(self.label_YMAX_O, 1, 2, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.groupBox_Control_OpenLoop)
        self.label_32.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_32.setObjectName("label_32")
        self.gridLayout_OpenLoop.addWidget(self.label_32, 2, 5, 1, 1)
        self.doubleSpinBox_ZTarget_O = QtWidgets.QDoubleSpinBox(self.groupBox_Control_OpenLoop)
        self.doubleSpinBox_ZTarget_O.setKeyboardTracking(False)
        self.doubleSpinBox_ZTarget_O.setMaximum(100.0)
        self.doubleSpinBox_ZTarget_O.setSingleStep(0.01)
        self.doubleSpinBox_ZTarget_O.setObjectName("doubleSpinBox_ZTarget_O")
        self.gridLayout_OpenLoop.addWidget(self.doubleSpinBox_ZTarget_O, 2, 4, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.groupBox_Control_OpenLoop)
        self.label_31.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_31.setObjectName("label_31")
        self.gridLayout_OpenLoop.addWidget(self.label_31, 1, 5, 1, 1)
        self.label_ZMIN_O = QtWidgets.QLabel(self.groupBox_Control_OpenLoop)
        self.label_ZMIN_O.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_ZMIN_O.setObjectName("label_ZMIN_O")
        self.gridLayout_OpenLoop.addWidget(self.label_ZMIN_O, 2, 1, 1, 1)
        self.gridLayout_OpenLoop.setColumnStretch(1, 1)
        self.gridLayout_OpenLoop.setColumnStretch(2, 1)
        self.gridLayout_OpenLoop.setColumnStretch(4, 1)
        self.gridLayout_OpenLoop.setColumnStretch(6, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_OpenLoop)
        self.verticalLayout_3.addWidget(self.groupBox_Control_OpenLoop)
        self.verticalLayout_2.addWidget(self.groupBox_Control_Online)
        self.verticalLayout_6.addWidget(self.groupBox_Control)
        spacerItem2 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem2)

        self.retranslateUi(Piezo_Config_Window)
        self.comboBox_COM_Parity.setCurrentIndex(0)
        self.comboBox_COM_Baudrate.setCurrentIndex(4)
        self.comboBox_COM_Stopbits.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Piezo_Config_Window)
        Piezo_Config_Window.setTabOrder(self.comboBox_COM, self.comboBox_COM_Baudrate)
        Piezo_Config_Window.setTabOrder(self.comboBox_COM_Baudrate, self.comboBox_COM_Parity)
        Piezo_Config_Window.setTabOrder(self.comboBox_COM_Parity, self.comboBox_COM_Stopbits)
        Piezo_Config_Window.setTabOrder(self.comboBox_COM_Stopbits, self.pushButton_COM_Refresh)
        Piezo_Config_Window.setTabOrder(self.pushButton_COM_Refresh, self.pushButton_COM_Open)
        Piezo_Config_Window.setTabOrder(self.pushButton_COM_Open, self.radioButton_Online)
        Piezo_Config_Window.setTabOrder(self.radioButton_Online, self.radioButton_Offline)
        Piezo_Config_Window.setTabOrder(self.radioButton_Offline, self.radioButton_ClosedLoop)
        Piezo_Config_Window.setTabOrder(self.radioButton_ClosedLoop, self.radioButton_OpenLoop)
        Piezo_Config_Window.setTabOrder(self.radioButton_OpenLoop, self.pushButton_Sync)
        Piezo_Config_Window.setTabOrder(self.pushButton_Sync, self.doubleSpinBox_XTarget_C)
        Piezo_Config_Window.setTabOrder(self.doubleSpinBox_XTarget_C, self.doubleSpinBox_YTarget_C)
        Piezo_Config_Window.setTabOrder(self.doubleSpinBox_YTarget_C, self.doubleSpinBox_ZTarget_C)
        Piezo_Config_Window.setTabOrder(self.doubleSpinBox_ZTarget_C, self.doubleSpinBox_XTarget_O)
        Piezo_Config_Window.setTabOrder(self.doubleSpinBox_XTarget_O, self.doubleSpinBox_YTarget_O)
        Piezo_Config_Window.setTabOrder(self.doubleSpinBox_YTarget_O, self.doubleSpinBox_ZTarget_O)

    def retranslateUi(self, Piezo_Config_Window):
        _translate = QtCore.QCoreApplication.translate
        Piezo_Config_Window.setWindowTitle(_translate("Piezo_Config_Window", "Piezo Configuration"))
        self.groupBox_COM.setTitle(_translate("Piezo_Config_Window", "Piezo COM"))
        self.label_22.setText(_translate("Piezo_Config_Window", "BaudRate:"))
        self.comboBox_COM_Parity.setItemText(0, _translate("Piezo_Config_Window", "None"))
        self.comboBox_COM_Parity.setItemText(1, _translate("Piezo_Config_Window", "ODD"))
        self.comboBox_COM_Parity.setItemText(2, _translate("Piezo_Config_Window", "EVEN"))
        self.label_21.setText(_translate("Piezo_Config_Window", "COM:"))
        self.comboBox_COM_Baudrate.setItemText(0, _translate("Piezo_Config_Window", "9600"))
        self.comboBox_COM_Baudrate.setItemText(1, _translate("Piezo_Config_Window", "19200"))
        self.comboBox_COM_Baudrate.setItemText(2, _translate("Piezo_Config_Window", "38400"))
        self.comboBox_COM_Baudrate.setItemText(3, _translate("Piezo_Config_Window", "57600"))
        self.comboBox_COM_Baudrate.setItemText(4, _translate("Piezo_Config_Window", "115200"))
        self.pushButton_COM_Open.setText(_translate("Piezo_Config_Window", "Open"))
        self.label_23.setText(_translate("Piezo_Config_Window", "Parity:"))
        self.pushButton_COM_Refresh.setText(_translate("Piezo_Config_Window", "Refresh"))
        self.label_24.setText(_translate("Piezo_Config_Window", "StopBits:"))
        self.comboBox_COM_Stopbits.setItemText(0, _translate("Piezo_Config_Window", "1"))
        self.comboBox_COM_Stopbits.setItemText(1, _translate("Piezo_Config_Window", "1.5"))
        self.comboBox_COM_Stopbits.setItemText(2, _translate("Piezo_Config_Window", "2"))
        self.groupBox_Control.setTitle(_translate("Piezo_Config_Window", "Piezo Control"))
        self.label_2.setText(_translate("Piezo_Config_Window", "Control Mode:"))
        self.radioButton_Online.setText(_translate("Piezo_Config_Window", "Online"))
        self.radioButton_Offline.setText(_translate("Piezo_Config_Window", "Offline"))
        self.groupBox_Control_Online.setTitle(_translate("Piezo_Config_Window", "Online"))
        self.label.setText(_translate("Piezo_Config_Window", "Mode:"))
        self.radioButton_ClosedLoop.setText(_translate("Piezo_Config_Window", "Closed Loop"))
        self.radioButton_OpenLoop.setText(_translate("Piezo_Config_Window", "Open Loop"))
        self.pushButton_Sync.setText(_translate("Piezo_Config_Window", "Get Axis Status"))
        self.groupBox_VelControl.setTitle(_translate("Piezo_Config_Window", "Velocity Control"))
        self.label_56.setText(_translate("Piezo_Config_Window", "X:"))
        self.checkBox_VelCtrlX.setText(_translate("Piezo_Config_Window", "Vel. Ctrl."))
        self.label_VelUnit.setText(_translate("Piezo_Config_Window", "um/s"))
        self.label_55.setText(_translate("Piezo_Config_Window", "Y:"))
        self.checkBox_VelCtrlY.setText(_translate("Piezo_Config_Window", "Vel. Ctrl."))
        self.label_54.setText(_translate("Piezo_Config_Window", "Z:"))
        self.checkBox_VelCtrlZ.setText(_translate("Piezo_Config_Window", "Vel. Ctrl."))
        self.pushButton_GetVel.setText(_translate("Piezo_Config_Window", "Get"))
        self.pushButton_SetVel.setText(_translate("Piezo_Config_Window", "Set"))
        self.groupBox_Control_ClosedLoop.setTitle(_translate("Piezo_Config_Window", "Closed Loop"))
        self.label_YMAX_C.setText(_translate("Piezo_Config_Window", "0.0"))
        self.label_47.setText(_translate("Piezo_Config_Window", "T:"))
        self.label_ZMAX_C.setText(_translate("Piezo_Config_Window", "0.0"))
        self.label_50.setText(_translate("Piezo_Config_Window", "T:"))
        self.label_XMAX_C.setText(_translate("Piezo_Config_Window", "0.0"))
        self.label_52.setText(_translate("Piezo_Config_Window", "C:"))
        self.label_XCurrentPos_C.setText(_translate("Piezo_Config_Window", "0.0"))
        self.label_53.setText(_translate("Piezo_Config_Window", "C:"))
        self.label_ZMIN_C.setText(_translate("Piezo_Config_Window", "0.0"))
        self.label_49.setText(_translate("Piezo_Config_Window", "C:"))
        self.label_YMIN_C.setText(_translate("Piezo_Config_Window", "0.0"))
        self.label_XMIN_C.setText(_translate("Piezo_Config_Window", "0.0"))
        self.label_45.setText(_translate("Piezo_Config_Window", "T:"))
        self.label_ZCurrentPos_C.setText(_translate("Piezo_Config_Window", "0.0"))
        self.label_YCurrentPos_C.setText(_translate("Piezo_Config_Window", "0.0"))
        self.label_46.setText(_translate("Piezo_Config_Window", "X(um):"))
        self.label_48.setText(_translate("Piezo_Config_Window", "Y(um):"))
        self.label_51.setText(_translate("Piezo_Config_Window", "Z(um):"))
        self.groupBox_Control_OpenLoop.setTitle(_translate("Piezo_Config_Window", "Open Loop"))
        self.label_YMIN_O.setText(_translate("Piezo_Config_Window", "0.0"))
        self.label_XMAX_O.setText(_translate("Piezo_Config_Window", "0.0"))
        self.label_29.setText(_translate("Piezo_Config_Window", "T:"))
        self.label_ZCurrentPos_O.setText(_translate("Piezo_Config_Window", "0.0"))
        self.label_33.setText(_translate("Piezo_Config_Window", "X(V):"))
        self.label_35.setText(_translate("Piezo_Config_Window", "T:"))
        self.label_28.setText(_translate("Piezo_Config_Window", "Y(V):"))
        self.label_ZMAX_O.setText(_translate("Piezo_Config_Window", "0.0"))
        self.label_30.setText(_translate("Piezo_Config_Window", "C:"))
        self.label_XMIN_O.setText(_translate("Piezo_Config_Window", "0.0"))
        self.label_XCurrentPos_O.setText(_translate("Piezo_Config_Window", "0.0"))
        self.label_YCurrentPos_O.setText(_translate("Piezo_Config_Window", "0.0"))
        self.label_27.setText(_translate("Piezo_Config_Window", "T:"))
        self.label_34.setText(_translate("Piezo_Config_Window", "Z(V):"))
        self.label_YMAX_O.setText(_translate("Piezo_Config_Window", "0.0"))
        self.label_32.setText(_translate("Piezo_Config_Window", "C:"))
        self.label_31.setText(_translate("Piezo_Config_Window", "C:"))
        self.label_ZMIN_O.setText(_translate("Piezo_Config_Window", "0.0"))
