# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'nidaq_config.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NIDAQ_Config_Window(object):
    def setupUi(self, NIDAQ_Config_Window):
        NIDAQ_Config_Window.setObjectName("NIDAQ_Config_Window")
        NIDAQ_Config_Window.resize(1067, 577)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(NIDAQ_Config_Window)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(NIDAQ_Config_Window)
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.pushButton_Conn = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_Conn.setToolTip("")
        self.pushButton_Conn.setCheckable(True)
        self.pushButton_Conn.setObjectName("pushButton_Conn")
        self.gridLayout_6.addWidget(self.pushButton_Conn, 1, 2, 1, 1)
        self.label_Conn_Status = QtWidgets.QLabel(self.groupBox)
        self.label_Conn_Status.setMinimumSize(QtCore.QSize(80, 0))
        self.label_Conn_Status.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_Conn_Status.setStyleSheet("background : red")
        self.label_Conn_Status.setText("")
        self.label_Conn_Status.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Conn_Status.setObjectName("label_Conn_Status")
        self.gridLayout_6.addWidget(self.label_Conn_Status, 1, 0, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.groupBox)
        self.label_38.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_38.setObjectName("label_38")
        self.gridLayout_6.addWidget(self.label_38, 0, 0, 1, 1)
        self.pushButton_Refresh = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_Refresh.setToolTip("")
        self.pushButton_Refresh.setObjectName("pushButton_Refresh")
        self.gridLayout_6.addWidget(self.pushButton_Refresh, 1, 1, 1, 1)
        self.comboBox_Device = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_Device.sizePolicy().hasHeightForWidth())
        self.comboBox_Device.setSizePolicy(sizePolicy)
        self.comboBox_Device.setMinimumSize(QtCore.QSize(320, 0))
        self.comboBox_Device.setObjectName("comboBox_Device")
        self.gridLayout_6.addWidget(self.comboBox_Device, 0, 1, 1, 2)
        self.verticalLayout_7.addLayout(self.gridLayout_6)
        self.horizontalLayout.addWidget(self.groupBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.groupBox_Control = QtWidgets.QGroupBox(NIDAQ_Config_Window)
        self.groupBox_Control.setEnabled(False)
        self.groupBox_Control.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_Control.setObjectName("groupBox_Control")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_Control)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.groupBox_Control)
        self.label_3.setFrameShape(QtWidgets.QFrame.Box)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 4, 1, 1)
        self.pushButton_ReadDi = QtWidgets.QPushButton(self.groupBox_Control)
        self.pushButton_ReadDi.setObjectName("pushButton_ReadDi")
        self.gridLayout.addWidget(self.pushButton_ReadDi, 0, 5, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_Control)
        self.label_4.setFrameShape(QtWidgets.QFrame.Box)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 6, 1, 1)
        self.pushButton_ReadAi = QtWidgets.QPushButton(self.groupBox_Control)
        self.pushButton_ReadAi.setObjectName("pushButton_ReadAi")
        self.gridLayout.addWidget(self.pushButton_ReadAi, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_Control)
        self.label_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.pushButton_WriteAo = QtWidgets.QPushButton(self.groupBox_Control)
        self.pushButton_WriteAo.setObjectName("pushButton_WriteAo")
        self.gridLayout.addWidget(self.pushButton_WriteAo, 0, 3, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.groupBox_Control)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 255, 418))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_AiChs = QtWidgets.QGridLayout()
        self.gridLayout_AiChs.setObjectName("gridLayout_AiChs")
        self.verticalLayout.addLayout(self.gridLayout_AiChs)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 1, 0, 2, 2)
        self.label = QtWidgets.QLabel(self.groupBox_Control)
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.pushButton_WriteDo = QtWidgets.QPushButton(self.groupBox_Control)
        self.pushButton_WriteDo.setObjectName("pushButton_WriteDo")
        self.gridLayout.addWidget(self.pushButton_WriteDo, 0, 7, 1, 1)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.groupBox_Control)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 254, 418))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_AoChs = QtWidgets.QGridLayout()
        self.gridLayout_AoChs.setObjectName("gridLayout_AoChs")
        self.verticalLayout_2.addLayout(self.gridLayout_AoChs)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout.addWidget(self.scrollArea_2, 1, 2, 2, 2)
        self.scrollArea_3 = QtWidgets.QScrollArea(self.groupBox_Control)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 255, 418))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_DiChs = QtWidgets.QGridLayout()
        self.gridLayout_DiChs.setObjectName("gridLayout_DiChs")
        self.verticalLayout_3.addLayout(self.gridLayout_DiChs)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.gridLayout.addWidget(self.scrollArea_3, 1, 4, 2, 2)
        self.scrollArea_4 = QtWidgets.QScrollArea(self.groupBox_Control)
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName("scrollArea_4")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 256, 418))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout_DoChs = QtWidgets.QGridLayout()
        self.gridLayout_DoChs.setObjectName("gridLayout_DoChs")
        self.verticalLayout_4.addLayout(self.gridLayout_DoChs)
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_4)
        self.gridLayout.addWidget(self.scrollArea_4, 1, 6, 2, 2)
        self.verticalLayout_5.addLayout(self.gridLayout)
        self.verticalLayout_6.addWidget(self.groupBox_Control)
        self.verticalLayout_6.setStretch(1, 1)

        self.retranslateUi(NIDAQ_Config_Window)
        QtCore.QMetaObject.connectSlotsByName(NIDAQ_Config_Window)
        NIDAQ_Config_Window.setTabOrder(self.comboBox_Device, self.pushButton_Refresh)
        NIDAQ_Config_Window.setTabOrder(self.pushButton_Refresh, self.pushButton_Conn)

    def retranslateUi(self, NIDAQ_Config_Window):
        _translate = QtCore.QCoreApplication.translate
        NIDAQ_Config_Window.setWindowTitle(_translate("NIDAQ_Config_Window", "NIDAQ Configuration"))
        self.groupBox.setTitle(_translate("NIDAQ_Config_Window", "NI DAQ Connection"))
        self.pushButton_Conn.setText(_translate("NIDAQ_Config_Window", "Open"))
        self.label_38.setText(_translate("NIDAQ_Config_Window", "Dev:"))
        self.pushButton_Refresh.setText(_translate("NIDAQ_Config_Window", "Refresh"))
        self.groupBox_Control.setTitle(_translate("NIDAQ_Config_Window", "NI DAQ Control"))
        self.label_3.setText(_translate("NIDAQ_Config_Window", "Digital Input:"))
        self.pushButton_ReadDi.setText(_translate("NIDAQ_Config_Window", "Read"))
        self.label_4.setText(_translate("NIDAQ_Config_Window", "Digital Output:"))
        self.pushButton_ReadAi.setText(_translate("NIDAQ_Config_Window", "Read"))
        self.label_2.setText(_translate("NIDAQ_Config_Window", "Analog Output:"))
        self.pushButton_WriteAo.setText(_translate("NIDAQ_Config_Window", "Write"))
        self.label.setText(_translate("NIDAQ_Config_Window", "Analog Input:"))
        self.pushButton_WriteDo.setText(_translate("NIDAQ_Config_Window", "Write"))


