# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'm3390_config.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_M3390_Config_Window(object):
    def setupUi(self, M3390_Config_Window):
        M3390_Config_Window.setObjectName("M3390_Config_Window")
        M3390_Config_Window.resize(531, 452)
        self.verticalLayout = QtWidgets.QVBoxLayout(M3390_Config_Window)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_Resource = QtWidgets.QGroupBox(M3390_Config_Window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_Resource.sizePolicy().hasHeightForWidth())
        self.groupBox_Resource.setSizePolicy(sizePolicy)
        self.groupBox_Resource.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_Resource.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.groupBox_Resource.setObjectName("groupBox_Resource")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_Resource)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(6, -1, 6, -1)
        self.gridLayout.setHorizontalSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupBox_Resource)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.comboBox_ResourceAddr = QtWidgets.QComboBox(self.groupBox_Resource)
        self.comboBox_ResourceAddr.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_ResourceAddr.sizePolicy().hasHeightForWidth())
        self.comboBox_ResourceAddr.setSizePolicy(sizePolicy)
        self.comboBox_ResourceAddr.setObjectName("comboBox_ResourceAddr")
        self.gridLayout.addWidget(self.comboBox_ResourceAddr, 0, 1, 1, 2)
        self.pushButton_Open = QtWidgets.QPushButton(self.groupBox_Resource)
        self.pushButton_Open.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_Open.setCheckable(True)
        self.pushButton_Open.setFlat(False)
        self.pushButton_Open.setObjectName("pushButton_Open")
        self.gridLayout.addWidget(self.pushButton_Open, 1, 2, 1, 1)
        self.pushButton_Refresh = QtWidgets.QPushButton(self.groupBox_Resource)
        self.pushButton_Refresh.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_Refresh.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_Refresh.setCheckable(False)
        self.pushButton_Refresh.setObjectName("pushButton_Refresh")
        self.gridLayout.addWidget(self.pushButton_Refresh, 1, 1, 1, 1)
        self.label_CONN_Status = QtWidgets.QLabel(self.groupBox_Resource)
        self.label_CONN_Status.setStyleSheet("background : red")
        self.label_CONN_Status.setText("")
        self.label_CONN_Status.setAlignment(QtCore.Qt.AlignCenter)
        self.label_CONN_Status.setObjectName("label_CONN_Status")
        self.gridLayout.addWidget(self.label_CONN_Status, 1, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.verticalLayout.addWidget(self.groupBox_Resource)
        self.groupBox_Settings = QtWidgets.QGroupBox(M3390_Config_Window)
        self.groupBox_Settings.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_Settings.sizePolicy().hasHeightForWidth())
        self.groupBox_Settings.setSizePolicy(sizePolicy)
        self.groupBox_Settings.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_Settings.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.groupBox_Settings.setObjectName("groupBox_Settings")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_Settings)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_Settings)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.pushButton_SetFunc = QtWidgets.QPushButton(self.groupBox_Settings)
        self.pushButton_SetFunc.setObjectName("pushButton_SetFunc")
        self.gridLayout_2.addWidget(self.pushButton_SetFunc, 0, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_Settings)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.doubleSpinBox_FrequencyValue = QtWidgets.QDoubleSpinBox(self.groupBox_Settings)
        self.doubleSpinBox_FrequencyValue.setKeyboardTracking(False)
        self.doubleSpinBox_FrequencyValue.setDecimals(4)
        self.doubleSpinBox_FrequencyValue.setMinimum(1.0)
        self.doubleSpinBox_FrequencyValue.setMaximum(50.0)
        self.doubleSpinBox_FrequencyValue.setObjectName("doubleSpinBox_FrequencyValue")
        self.gridLayout_2.addWidget(self.doubleSpinBox_FrequencyValue, 1, 1, 1, 1)
        self.comboBox_FrequencyUnit = QtWidgets.QComboBox(self.groupBox_Settings)
        self.comboBox_FrequencyUnit.setObjectName("comboBox_FrequencyUnit")
        self.comboBox_FrequencyUnit.addItem("")
        self.comboBox_FrequencyUnit.addItem("")
        self.comboBox_FrequencyUnit.addItem("")
        self.comboBox_FrequencyUnit.addItem("")
        self.comboBox_FrequencyUnit.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_FrequencyUnit, 1, 2, 1, 1)
        self.pushButton_SetFreq = QtWidgets.QPushButton(self.groupBox_Settings)
        self.pushButton_SetFreq.setObjectName("pushButton_SetFreq")
        self.gridLayout_2.addWidget(self.pushButton_SetFreq, 1, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_Settings)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 2, 0, 1, 1)
        self.pushButton_SetVolUnit = QtWidgets.QPushButton(self.groupBox_Settings)
        self.pushButton_SetVolUnit.setObjectName("pushButton_SetVolUnit")
        self.gridLayout_2.addWidget(self.pushButton_SetVolUnit, 2, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_Settings)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 3, 0, 1, 1)
        self.doubleSpinBox_SigAmpValue = QtWidgets.QDoubleSpinBox(self.groupBox_Settings)
        self.doubleSpinBox_SigAmpValue.setKeyboardTracking(False)
        self.doubleSpinBox_SigAmpValue.setDecimals(4)
        self.doubleSpinBox_SigAmpValue.setMaximum(1000.0)
        self.doubleSpinBox_SigAmpValue.setObjectName("doubleSpinBox_SigAmpValue")
        self.gridLayout_2.addWidget(self.doubleSpinBox_SigAmpValue, 3, 1, 1, 1)
        self.comboBox_SigAmpUnit = QtWidgets.QComboBox(self.groupBox_Settings)
        self.comboBox_SigAmpUnit.setObjectName("comboBox_SigAmpUnit")
        self.comboBox_SigAmpUnit.addItem("")
        self.comboBox_SigAmpUnit.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_SigAmpUnit, 3, 2, 1, 1)
        self.pushButton_SetSigAmp = QtWidgets.QPushButton(self.groupBox_Settings)
        self.pushButton_SetSigAmp.setObjectName("pushButton_SetSigAmp")
        self.gridLayout_2.addWidget(self.pushButton_SetSigAmp, 3, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_Settings)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 4, 0, 1, 1)
        self.doubleSpinBox_SigOffsetValue = QtWidgets.QDoubleSpinBox(self.groupBox_Settings)
        self.doubleSpinBox_SigOffsetValue.setKeyboardTracking(False)
        self.doubleSpinBox_SigOffsetValue.setDecimals(4)
        self.doubleSpinBox_SigOffsetValue.setMaximum(1000.0)
        self.doubleSpinBox_SigOffsetValue.setObjectName("doubleSpinBox_SigOffsetValue")
        self.gridLayout_2.addWidget(self.doubleSpinBox_SigOffsetValue, 4, 1, 1, 1)
        self.comboBox_SigOffsetUnit = QtWidgets.QComboBox(self.groupBox_Settings)
        self.comboBox_SigOffsetUnit.setObjectName("comboBox_SigOffsetUnit")
        self.comboBox_SigOffsetUnit.addItem("")
        self.comboBox_SigOffsetUnit.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_SigOffsetUnit, 4, 2, 1, 1)
        self.pushButton_SetSigOffset = QtWidgets.QPushButton(self.groupBox_Settings)
        self.pushButton_SetSigOffset.setObjectName("pushButton_SetSigOffset")
        self.gridLayout_2.addWidget(self.pushButton_SetSigOffset, 4, 3, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_Settings)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 5, 0, 1, 1)
        self.radioButton_OutputOn = QtWidgets.QRadioButton(self.groupBox_Settings)
        self.radioButton_OutputOn.setObjectName("radioButton_OutputOn")
        self.gridLayout_2.addWidget(self.radioButton_OutputOn, 5, 1, 1, 1)
        self.radioButton_OutputOff = QtWidgets.QRadioButton(self.groupBox_Settings)
        self.radioButton_OutputOff.setChecked(True)
        self.radioButton_OutputOff.setObjectName("radioButton_OutputOff")
        self.gridLayout_2.addWidget(self.radioButton_OutputOff, 5, 2, 1, 1)
        self.comboBox_Function = QtWidgets.QComboBox(self.groupBox_Settings)
        self.comboBox_Function.setObjectName("comboBox_Function")
        self.comboBox_Function.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_Function, 0, 1, 1, 2)
        self.comboBox_VoltageUnit = QtWidgets.QComboBox(self.groupBox_Settings)
        self.comboBox_VoltageUnit.setObjectName("comboBox_VoltageUnit")
        self.comboBox_VoltageUnit.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_VoltageUnit, 2, 1, 1, 2)
        self.gridLayout_2.setColumnStretch(1, 1)
        self.gridLayout_2.setColumnStretch(2, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        self.verticalLayout.addWidget(self.groupBox_Settings)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.retranslateUi(M3390_Config_Window)
        self.comboBox_FrequencyUnit.setCurrentIndex(0)
        self.comboBox_SigAmpUnit.setCurrentIndex(0)
        self.comboBox_SigOffsetUnit.setCurrentIndex(0)
        self.comboBox_Function.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(M3390_Config_Window)

    def retranslateUi(self, M3390_Config_Window):
        _translate = QtCore.QCoreApplication.translate
        M3390_Config_Window.setWindowTitle(_translate("M3390_Config_Window", "Keithley 3390 Configuration"))
        self.groupBox_Resource.setTitle(_translate("M3390_Config_Window", "Keithley 3390 CONN"))
        self.label.setText(_translate("M3390_Config_Window", "Resource Addr:"))
        self.pushButton_Open.setText(_translate("M3390_Config_Window", "Open"))
        self.pushButton_Refresh.setText(_translate("M3390_Config_Window", "Refresh"))
        self.groupBox_Settings.setTitle(_translate("M3390_Config_Window", "Keithley 3390 Settings"))
        self.label_2.setText(_translate("M3390_Config_Window", "Function:"))
        self.pushButton_SetFunc.setText(_translate("M3390_Config_Window", "Set"))
        self.label_3.setText(_translate("M3390_Config_Window", "Frequency:"))
        self.comboBox_FrequencyUnit.setItemText(0, _translate("M3390_Config_Window", "uHz"))
        self.comboBox_FrequencyUnit.setItemText(1, _translate("M3390_Config_Window", "mHz"))
        self.comboBox_FrequencyUnit.setItemText(2, _translate("M3390_Config_Window", "Hz"))
        self.comboBox_FrequencyUnit.setItemText(3, _translate("M3390_Config_Window", "kHz"))
        self.comboBox_FrequencyUnit.setItemText(4, _translate("M3390_Config_Window", "MHz"))
        self.pushButton_SetFreq.setText(_translate("M3390_Config_Window", "Set"))
        self.label_4.setText(_translate("M3390_Config_Window", "Voltage Unit:"))
        self.pushButton_SetVolUnit.setText(_translate("M3390_Config_Window", "Set"))
        self.label_5.setText(_translate("M3390_Config_Window", "Signal Amplitude:"))
        self.comboBox_SigAmpUnit.setItemText(0, _translate("M3390_Config_Window", "mV"))
        self.comboBox_SigAmpUnit.setItemText(1, _translate("M3390_Config_Window", "V"))
        self.pushButton_SetSigAmp.setText(_translate("M3390_Config_Window", "Set"))
        self.label_6.setText(_translate("M3390_Config_Window", "Signal Offset:"))
        self.comboBox_SigOffsetUnit.setItemText(0, _translate("M3390_Config_Window", "mV"))
        self.comboBox_SigOffsetUnit.setItemText(1, _translate("M3390_Config_Window", "V"))
        self.pushButton_SetSigOffset.setText(_translate("M3390_Config_Window", "Set"))
        self.label_12.setText(_translate("M3390_Config_Window", "Output:"))
        self.radioButton_OutputOn.setText(_translate("M3390_Config_Window", "ON"))
        self.radioButton_OutputOff.setText(_translate("M3390_Config_Window", "OFF"))
        self.comboBox_Function.setItemText(0, _translate("M3390_Config_Window", "SINusoid"))
        self.comboBox_VoltageUnit.setItemText(0, _translate("M3390_Config_Window", "Vpp"))


