# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CVCameraConfig.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_CVCameraConfig(object):
    def setupUi(self, Form_CVCameraConfig):
        Form_CVCameraConfig.setObjectName("Form_CVCameraConfig")
        Form_CVCameraConfig.resize(513, 683)
        Form_CVCameraConfig.setStyleSheet("")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form_CVCameraConfig)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(12)
        self.gridLayout.setObjectName("gridLayout")
        self.label_12 = QtWidgets.QLabel(Form_CVCameraConfig)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 8, 0, 1, 1)
        self.doubleSpinBox_Gain = QtWidgets.QDoubleSpinBox(Form_CVCameraConfig)
        self.doubleSpinBox_Gain.setMinimumSize(QtCore.QSize(120, 0))
        self.doubleSpinBox_Gain.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_Gain.setKeyboardTracking(False)
        self.doubleSpinBox_Gain.setDecimals(1)
        self.doubleSpinBox_Gain.setMinimum(-10000.0)
        self.doubleSpinBox_Gain.setMaximum(10000.0)
        self.doubleSpinBox_Gain.setSingleStep(1.0)
        self.doubleSpinBox_Gain.setObjectName("doubleSpinBox_Gain")
        self.gridLayout.addWidget(self.doubleSpinBox_Gain, 6, 3, 1, 1)
        self.label_14 = QtWidgets.QLabel(Form_CVCameraConfig)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 9, 0, 1, 1)
        self.doubleSpinBox_Contrast = QtWidgets.QDoubleSpinBox(Form_CVCameraConfig)
        self.doubleSpinBox_Contrast.setMinimumSize(QtCore.QSize(120, 0))
        self.doubleSpinBox_Contrast.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_Contrast.setKeyboardTracking(False)
        self.doubleSpinBox_Contrast.setDecimals(1)
        self.doubleSpinBox_Contrast.setMinimum(-10000.0)
        self.doubleSpinBox_Contrast.setMaximum(10000.0)
        self.doubleSpinBox_Contrast.setSingleStep(1.0)
        self.doubleSpinBox_Contrast.setObjectName("doubleSpinBox_Contrast")
        self.gridLayout.addWidget(self.doubleSpinBox_Contrast, 3, 3, 1, 1)
        self.doubleSpinBox_Exposure = QtWidgets.QDoubleSpinBox(Form_CVCameraConfig)
        self.doubleSpinBox_Exposure.setMinimumSize(QtCore.QSize(120, 0))
        self.doubleSpinBox_Exposure.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_Exposure.setKeyboardTracking(False)
        self.doubleSpinBox_Exposure.setDecimals(1)
        self.doubleSpinBox_Exposure.setMinimum(-10000.0)
        self.doubleSpinBox_Exposure.setMaximum(10000.0)
        self.doubleSpinBox_Exposure.setSingleStep(1.0)
        self.doubleSpinBox_Exposure.setObjectName("doubleSpinBox_Exposure")
        self.gridLayout.addWidget(self.doubleSpinBox_Exposure, 7, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(Form_CVCameraConfig)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 5, 0, 1, 1)
        self.doubleSpinBox_Hue = QtWidgets.QDoubleSpinBox(Form_CVCameraConfig)
        self.doubleSpinBox_Hue.setMinimumSize(QtCore.QSize(120, 0))
        self.doubleSpinBox_Hue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_Hue.setKeyboardTracking(False)
        self.doubleSpinBox_Hue.setDecimals(1)
        self.doubleSpinBox_Hue.setMinimum(-10000.0)
        self.doubleSpinBox_Hue.setMaximum(10000.0)
        self.doubleSpinBox_Hue.setSingleStep(1.0)
        self.doubleSpinBox_Hue.setObjectName("doubleSpinBox_Hue")
        self.gridLayout.addWidget(self.doubleSpinBox_Hue, 5, 3, 1, 1)
        self.doubleSpinBox_Saturation = QtWidgets.QDoubleSpinBox(Form_CVCameraConfig)
        self.doubleSpinBox_Saturation.setMinimumSize(QtCore.QSize(120, 0))
        self.doubleSpinBox_Saturation.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_Saturation.setKeyboardTracking(False)
        self.doubleSpinBox_Saturation.setDecimals(1)
        self.doubleSpinBox_Saturation.setMinimum(-10000.0)
        self.doubleSpinBox_Saturation.setMaximum(10000.0)
        self.doubleSpinBox_Saturation.setSingleStep(1.0)
        self.doubleSpinBox_Saturation.setObjectName("doubleSpinBox_Saturation")
        self.gridLayout.addWidget(self.doubleSpinBox_Saturation, 4, 3, 1, 1)
        self.doubleSpinBox_Zoom = QtWidgets.QDoubleSpinBox(Form_CVCameraConfig)
        self.doubleSpinBox_Zoom.setMinimumSize(QtCore.QSize(120, 0))
        self.doubleSpinBox_Zoom.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_Zoom.setKeyboardTracking(False)
        self.doubleSpinBox_Zoom.setDecimals(1)
        self.doubleSpinBox_Zoom.setMinimum(-10000.0)
        self.doubleSpinBox_Zoom.setMaximum(10000.0)
        self.doubleSpinBox_Zoom.setSingleStep(1.0)
        self.doubleSpinBox_Zoom.setObjectName("doubleSpinBox_Zoom")
        self.gridLayout.addWidget(self.doubleSpinBox_Zoom, 12, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(Form_CVCameraConfig)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(Form_CVCameraConfig)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 13, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(Form_CVCameraConfig)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(Form_CVCameraConfig)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 7, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(Form_CVCameraConfig)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 6, 0, 1, 1)
        self.doubleSpinBox_Focus = QtWidgets.QDoubleSpinBox(Form_CVCameraConfig)
        self.doubleSpinBox_Focus.setMinimumSize(QtCore.QSize(120, 0))
        self.doubleSpinBox_Focus.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_Focus.setKeyboardTracking(False)
        self.doubleSpinBox_Focus.setDecimals(1)
        self.doubleSpinBox_Focus.setMinimum(-10000.0)
        self.doubleSpinBox_Focus.setMaximum(10000.0)
        self.doubleSpinBox_Focus.setSingleStep(1.0)
        self.doubleSpinBox_Focus.setObjectName("doubleSpinBox_Focus")
        self.gridLayout.addWidget(self.doubleSpinBox_Focus, 13, 3, 1, 1)
        self.doubleSpinBox_Sharpness = QtWidgets.QDoubleSpinBox(Form_CVCameraConfig)
        self.doubleSpinBox_Sharpness.setMinimumSize(QtCore.QSize(120, 0))
        self.doubleSpinBox_Sharpness.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_Sharpness.setKeyboardTracking(False)
        self.doubleSpinBox_Sharpness.setDecimals(1)
        self.doubleSpinBox_Sharpness.setMinimum(-10000.0)
        self.doubleSpinBox_Sharpness.setMaximum(10000.0)
        self.doubleSpinBox_Sharpness.setSingleStep(1.0)
        self.doubleSpinBox_Sharpness.setObjectName("doubleSpinBox_Sharpness")
        self.gridLayout.addWidget(self.doubleSpinBox_Sharpness, 9, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(Form_CVCameraConfig)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.doubleSpinBox_Gamma = QtWidgets.QDoubleSpinBox(Form_CVCameraConfig)
        self.doubleSpinBox_Gamma.setMinimumSize(QtCore.QSize(120, 0))
        self.doubleSpinBox_Gamma.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_Gamma.setKeyboardTracking(False)
        self.doubleSpinBox_Gamma.setDecimals(1)
        self.doubleSpinBox_Gamma.setMinimum(-10000.0)
        self.doubleSpinBox_Gamma.setMaximum(10000.0)
        self.doubleSpinBox_Gamma.setSingleStep(1.0)
        self.doubleSpinBox_Gamma.setObjectName("doubleSpinBox_Gamma")
        self.gridLayout.addWidget(self.doubleSpinBox_Gamma, 10, 3, 1, 1)
        self.doubleSpinBox_Brightness = QtWidgets.QDoubleSpinBox(Form_CVCameraConfig)
        self.doubleSpinBox_Brightness.setMinimumSize(QtCore.QSize(150, 0))
        self.doubleSpinBox_Brightness.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_Brightness.setKeyboardTracking(False)
        self.doubleSpinBox_Brightness.setDecimals(1)
        self.doubleSpinBox_Brightness.setMinimum(-10000.0)
        self.doubleSpinBox_Brightness.setMaximum(10000.0)
        self.doubleSpinBox_Brightness.setSingleStep(1.0)
        self.doubleSpinBox_Brightness.setObjectName("doubleSpinBox_Brightness")
        self.gridLayout.addWidget(self.doubleSpinBox_Brightness, 2, 3, 1, 1)
        self.doubleSpinBox_AutoExposure = QtWidgets.QDoubleSpinBox(Form_CVCameraConfig)
        self.doubleSpinBox_AutoExposure.setMinimumSize(QtCore.QSize(0, 0))
        self.doubleSpinBox_AutoExposure.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_AutoExposure.setKeyboardTracking(False)
        self.doubleSpinBox_AutoExposure.setDecimals(1)
        self.doubleSpinBox_AutoExposure.setMinimum(0.0)
        self.doubleSpinBox_AutoExposure.setMaximum(100.0)
        self.doubleSpinBox_AutoExposure.setSingleStep(1.0)
        self.doubleSpinBox_AutoExposure.setObjectName("doubleSpinBox_AutoExposure")
        self.gridLayout.addWidget(self.doubleSpinBox_AutoExposure, 7, 2, 1, 1)
        self.label = QtWidgets.QLabel(Form_CVCameraConfig)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(Form_CVCameraConfig)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 12, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(Form_CVCameraConfig)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 4, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(Form_CVCameraConfig)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 10, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(Form_CVCameraConfig)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 11, 0, 1, 1)
        self.doubleSpinBox_Temperature = QtWidgets.QDoubleSpinBox(Form_CVCameraConfig)
        self.doubleSpinBox_Temperature.setMinimumSize(QtCore.QSize(120, 0))
        self.doubleSpinBox_Temperature.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_Temperature.setKeyboardTracking(False)
        self.doubleSpinBox_Temperature.setDecimals(1)
        self.doubleSpinBox_Temperature.setMinimum(-10000.0)
        self.doubleSpinBox_Temperature.setMaximum(10000.0)
        self.doubleSpinBox_Temperature.setSingleStep(1.0)
        self.doubleSpinBox_Temperature.setObjectName("doubleSpinBox_Temperature")
        self.gridLayout.addWidget(self.doubleSpinBox_Temperature, 11, 3, 1, 1)
        self.pushButton_SetFrameSize = QtWidgets.QPushButton(Form_CVCameraConfig)
        self.pushButton_SetFrameSize.setObjectName("pushButton_SetFrameSize")
        self.gridLayout.addWidget(self.pushButton_SetFrameSize, 0, 3, 2, 1)
        self.label_29 = QtWidgets.QLabel(Form_CVCameraConfig)
        self.label_29.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_29.setObjectName("label_29")
        self.gridLayout.addWidget(self.label_29, 7, 1, 1, 1)
        self.checkBox_Monochrome = QtWidgets.QCheckBox(Form_CVCameraConfig)
        self.checkBox_Monochrome.setObjectName("checkBox_Monochrome")
        self.gridLayout.addWidget(self.checkBox_Monochrome, 8, 1, 1, 3)
        self.checkBox_WBAuto = QtWidgets.QCheckBox(Form_CVCameraConfig)
        self.checkBox_WBAuto.setObjectName("checkBox_WBAuto")
        self.gridLayout.addWidget(self.checkBox_WBAuto, 11, 1, 1, 2)
        self.checkBox_FocusAuto = QtWidgets.QCheckBox(Form_CVCameraConfig)
        self.checkBox_FocusAuto.setObjectName("checkBox_FocusAuto")
        self.gridLayout.addWidget(self.checkBox_FocusAuto, 13, 1, 1, 2)
        self.lineEdit_FrameWidth = QtWidgets.QLineEdit(Form_CVCameraConfig)
        self.lineEdit_FrameWidth.setMinimumSize(QtCore.QSize(120, 0))
        self.lineEdit_FrameWidth.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_FrameWidth.setObjectName("lineEdit_FrameWidth")
        self.gridLayout.addWidget(self.lineEdit_FrameWidth, 0, 1, 1, 2)
        self.lineEdit_FrameHeight = QtWidgets.QLineEdit(Form_CVCameraConfig)
        self.lineEdit_FrameHeight.setMinimumSize(QtCore.QSize(120, 0))
        self.lineEdit_FrameHeight.setStyleSheet("")
        self.lineEdit_FrameHeight.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_FrameHeight.setObjectName("lineEdit_FrameHeight")
        self.gridLayout.addWidget(self.lineEdit_FrameHeight, 1, 1, 1, 2)
        self.horizontalLayout_2.addLayout(self.gridLayout)
        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)

        self.retranslateUi(Form_CVCameraConfig)
        QtCore.QMetaObject.connectSlotsByName(Form_CVCameraConfig)
        Form_CVCameraConfig.setTabOrder(self.lineEdit_FrameWidth, self.lineEdit_FrameHeight)
        Form_CVCameraConfig.setTabOrder(self.lineEdit_FrameHeight, self.pushButton_SetFrameSize)
        Form_CVCameraConfig.setTabOrder(self.pushButton_SetFrameSize, self.doubleSpinBox_Brightness)
        Form_CVCameraConfig.setTabOrder(self.doubleSpinBox_Brightness, self.doubleSpinBox_Contrast)
        Form_CVCameraConfig.setTabOrder(self.doubleSpinBox_Contrast, self.doubleSpinBox_Saturation)
        Form_CVCameraConfig.setTabOrder(self.doubleSpinBox_Saturation, self.doubleSpinBox_Hue)
        Form_CVCameraConfig.setTabOrder(self.doubleSpinBox_Hue, self.doubleSpinBox_Gain)
        Form_CVCameraConfig.setTabOrder(self.doubleSpinBox_Gain, self.doubleSpinBox_AutoExposure)
        Form_CVCameraConfig.setTabOrder(self.doubleSpinBox_AutoExposure, self.doubleSpinBox_Exposure)
        Form_CVCameraConfig.setTabOrder(self.doubleSpinBox_Exposure, self.checkBox_Monochrome)
        Form_CVCameraConfig.setTabOrder(self.checkBox_Monochrome, self.doubleSpinBox_Sharpness)
        Form_CVCameraConfig.setTabOrder(self.doubleSpinBox_Sharpness, self.doubleSpinBox_Gamma)
        Form_CVCameraConfig.setTabOrder(self.doubleSpinBox_Gamma, self.checkBox_WBAuto)
        Form_CVCameraConfig.setTabOrder(self.checkBox_WBAuto, self.doubleSpinBox_Temperature)
        Form_CVCameraConfig.setTabOrder(self.doubleSpinBox_Temperature, self.doubleSpinBox_Zoom)
        Form_CVCameraConfig.setTabOrder(self.doubleSpinBox_Zoom, self.checkBox_FocusAuto)
        Form_CVCameraConfig.setTabOrder(self.checkBox_FocusAuto, self.doubleSpinBox_Focus)

    def retranslateUi(self, Form_CVCameraConfig):
        _translate = QtCore.QCoreApplication.translate
        Form_CVCameraConfig.setWindowTitle(_translate("Form_CVCameraConfig", "Form"))
        self.label_12.setText(_translate("Form_CVCameraConfig", "Monochrome:"))
        self.label_14.setText(_translate("Form_CVCameraConfig", "Sharpness:"))
        self.label_9.setText(_translate("Form_CVCameraConfig", "Hue:"))
        self.label_4.setText(_translate("Form_CVCameraConfig", "Contrast:"))
        self.label_10.setText(_translate("Form_CVCameraConfig", "Focus:"))
        self.label_3.setText(_translate("Form_CVCameraConfig", "Brightness:"))
        self.label_15.setText(_translate("Form_CVCameraConfig", "Exposure:"))
        self.label_16.setText(_translate("Form_CVCameraConfig", "Gain:"))
        self.label_2.setText(_translate("Form_CVCameraConfig", "Height:"))
        self.label.setText(_translate("Form_CVCameraConfig", "Width:"))
        self.label_7.setText(_translate("Form_CVCameraConfig", "Zoom:"))
        self.label_8.setText(_translate("Form_CVCameraConfig", "Saturation:"))
        self.label_13.setText(_translate("Form_CVCameraConfig", "Gamma:"))
        self.label_11.setText(_translate("Form_CVCameraConfig", "Temperature:"))
        self.pushButton_SetFrameSize.setText(_translate("Form_CVCameraConfig", "Set Size"))
        self.label_29.setText(_translate("Form_CVCameraConfig", "A:"))
        self.checkBox_Monochrome.setText(_translate("Form_CVCameraConfig", "Monochrome"))
        self.checkBox_WBAuto.setText(_translate("Form_CVCameraConfig", "Auto"))
        self.checkBox_FocusAuto.setText(_translate("Form_CVCameraConfig", "Auto"))


